# _nb_export.py
# Section: Export tab cell
# Part of model_builder_notebook.py — assembled by build_notebook.py

@app.cell
def _export_display(config_dict, fit_result, output_dir, json, mo, main_tab):
    mo.stop(main_tab.value != "Export", None)
    _config_str = json.dumps(config_dict, indent=2)
    _fitted_str = json.dumps(fit_result.best_params if fit_result is not None else {}, indent=2)

    _script = """\
#!/usr/bin/env python3
\"\"\"
Generated by CLT Model Builder Notebook.
Usage: python run_simulation.py
\"\"\"

import sys
import json
import copy
import numpy as np
import pandas as pd
import sqlite3
from pathlib import Path
from types import SimpleNamespace

# ---- Configurable ----
MODEL_CONFIG_FILE = "model_config.json"
FITTED_PARAMS_FILE = "fitted_params.json"  # set to None to skip
OUTPUT_DIR = Path("simulation_output")
NUM_DAYS = 100
NUM_REPS = 1
STOCHASTIC = False
TIMESTEPS_PER_DAY = 7
START_DATE = "2024-01-01"
NUM_AGE_GROUPS = 1
NUM_RISK_GROUPS = 1

# Define scenarios: {name: {param: value}}
SCENARIOS = {
    "baseline": {},
    # "high_beta": {"beta_baseline": 0.4},
}

# ---- Setup ----
_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE.parent.parent))

import clt_toolkit as clt
import flu_core as flu
from generic_core.config_parser import parse_model_config_from_dict
from generic_core.generic_model import (
    ConfigDrivenSubpopModel, build_state_from_config, build_params_from_config,
)
from generic_core.generic_metapop import ConfigDrivenMetapopModel

with open(_HERE / MODEL_CONFIG_FILE) as _f:
    config_dict = json.load(_f)

if FITTED_PARAMS_FILE is not None:
    _fp = _HERE / FITTED_PARAMS_FILE
    if _fp.exists():
        with open(_fp) as _f:
            _fitted = json.load(_f)
        config_dict["params"] = {**config_dict.get("params", {}), **_fitted}
    else:
        print(f"Warning: {FITTED_PARAMS_FILE} not found")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _build_schedules(start_date, num_days):
    _h = max(num_days + 14, 370)
    _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
    _mob = json.dumps(np.ones((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    _vax = json.dumps(np.zeros((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    return SimpleNamespace(
        absolute_humidity_df=pd.DataFrame({"date": _dates, "absolute_humidity": [0.01] * _h}),
        school_work_calendar_df=pd.DataFrame({"date": _dates, "is_school_day": [1.0] * _h, "is_work_day": [1.0] * _h}),
        mobility_df=pd.DataFrame({"day_of_week": ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"], "mobility_modifier": [_mob]*7}),
        daily_vaccines_df=pd.DataFrame({"date": _dates, "daily_vaccines": [_vax] * _h}),
    )


def build_model(cfg, param_overrides, rep):
    _cfg = copy.deepcopy(cfg)
    if param_overrides:
        _cfg["params"] = {**_cfg.get("params", {}), **param_overrides}
    _sched = _build_schedules(START_DATE, NUM_DAYS)
    _mc = parse_model_config_from_dict(_cfg, schedules_input=_sched)
    _A, _R = NUM_AGE_GROUPS, NUM_RISK_GROUPS
    _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
    _first = _comps[0] if _comps else "S"
    _N = _cfg.get("total_population", 100000)
    _comp_init = {_first: np.full((_A, _R), float(_N))}
    for _c in _comps[1:]:
        _comp_init.setdefault(_c, np.zeros((_A, _R)))
    _state = build_state_from_config(_mc, _comp_init, epi_metric_init={})
    _params = build_params_from_config(_mc, num_age_groups=_A, num_risk_groups=_R)
    _tt = clt.TransitionTypes.BINOM if STOCHASTIC else clt.TransitionTypes.BINOM_DETERMINISTIC_NO_ROUND
    _settings = clt.SimulationSettings(
        timesteps_per_day=TIMESTEPS_PER_DAY, transition_type=_tt,
        start_real_date=START_DATE, save_daily_history=True,
    )
    _subpop = ConfigDrivenSubpopModel(
        model_config=_mc, state_init=_state, params=_params,
        simulation_settings=_settings, RNG=np.random.default_rng(rep),
        schedules_input=_sched, name="pop",
    )
    _mixing = flu.FluMixingParams(travel_proportions=np.array([[1.0]]), num_locations=1)
    return ConfigDrivenMetapopModel({"pop": _subpop}, mixing_params=_mixing)


all_results = {}
for scenario_name, overrides in SCENARIOS.items():
    print(f"Running scenario: {scenario_name}")
    _reps_data = []
    for _rep in range(NUM_REPS):
        _m = build_model(config_dict, overrides, _rep)
        _m.simulate_until_day(NUM_DAYS)
        _sps = list(_m.subpop_models.values())
        _h = {}
        for _sp in _sps:
            for _c, _comp in _sp.compartments.items():
                _arr = np.array(_comp.history_vals_list).sum(axis=(1, 2))
                _h[_c] = _h.get(_c, 0) + _arr
        _reps_data.append(_h)
    all_results[scenario_name] = _reps_data

_db = OUTPUT_DIR / "results.db"
_con = sqlite3.connect(_db)
_cur = _con.cursor()
_cur.execute(
    "CREATE TABLE IF NOT EXISTS results "
    "(scenario TEXT, rep INTEGER, compartment TEXT, day INTEGER, value REAL)"
)
for _scen, _reps_data in all_results.items():
    for _ri, _h in enumerate(_reps_data):
        for _c, _arr in _h.items():
            _cur.executemany(
                "INSERT INTO results VALUES (?,?,?,?,?)",
                [(_scen, _ri, _c, _d + 1, float(_v)) for _d, _v in enumerate(_arr)],
            )
_con.commit()
_con.close()
print(f"Results saved to {_db}")
"""

    _config_dl = mo.download(
        data=_config_str.encode(), filename="model_config.json",
        label="Download model_config.json", mimetype="application/json",
    )
    _script_dl = mo.download(
        data=_script.encode(), filename="run_simulation.py",
        label="Download run_simulation.py", mimetype="text/x-python",
    )
    _fitted_dl = mo.download(
        data=_fitted_str.encode(), filename="fitted_params.json",
        label="Download fitted_params.json", mimetype="application/json",
    )
    mo.vstack([
        mo.md("## Export"),
        mo.md("### Generated script  *(edit `SCENARIOS` and top constants before running)*"),
        mo.accordion({"run_simulation.py": mo.md(f"```python\n{_script}\n```")}),
        mo.md("### Downloads"),
        mo.hstack([_config_dl, _script_dl, _fitted_dl], justify="start"),
        mo.md(f"*Outputs auto-saved to `{output_dir}/`*"),
    ])
    return


# ============================================================
# Analysis tab — sub-tab selector (must depend only on mo)
# ============================================================

