# _nb_export.py
# Section: Export tab cell
# Part of model_builder_notebook.py — assembled by build_notebook.py

@app.cell
def _export_display(config_dict, fit_result, output_dir, json, mo, main_tab, num_age_groups, num_risk_groups, sim_days, sim_mode, n_reps, timesteps, start_date_input, analysis_scenarios, step_header, section_card, CLT_ACCENT):
    mo.stop(main_tab.value != "Export", None)
    _ACC = CLT_ACCENT["export"]
    _config_str = json.dumps(config_dict, indent=2)
    _fitted_str = json.dumps(fit_result.best_params if fit_result is not None else {}, indent=2)

    _script = """\
#!/usr/bin/env python3
\"\"\"
Generated by CLT Model Builder Notebook.
Usage: python run_simulation.py
\"\"\"

import sys
import json
import copy
import numpy as np
import pandas as pd
import sqlite3
from pathlib import Path
from types import SimpleNamespace

# ---- Configurable ----
MODEL_CONFIG_FILE = "model_config.json"
FITTED_PARAMS_FILE = "fitted_params.json"  # set to None to skip
OUTPUT_DIR = Path("simulation_output")
NUM_DAYS = 100
NUM_REPS = 1
STOCHASTIC = False
TIMESTEPS_PER_DAY = 7
START_DATE = "2024-01-01"
NUM_AGE_GROUPS = 1
NUM_RISK_GROUPS = 1

# <<<SCENARIOS_BLOCK>>>

# <<<SUBPOP_OVERRIDES_BLOCK>>>

# ---- Setup ----
_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE.parent.parent))

import clt_toolkit as clt
import flu_core as flu
from generic_core.config_parser import parse_model_config_from_dict
from generic_core.generic_model import (
    ConfigDrivenSubpopModel, build_state_from_config, build_params_from_config,
)
from generic_core.generic_metapop import ConfigDrivenMetapopModel

with open(_HERE / MODEL_CONFIG_FILE) as _f:
    config_dict = json.load(_f)

if FITTED_PARAMS_FILE is not None:
    _fp = _HERE / FITTED_PARAMS_FILE
    if _fp.exists():
        with open(_fp) as _f:
            _fitted = json.load(_f)
        config_dict["params"] = {**config_dict.get("params", {}), **_fitted}
    else:
        print(f"Warning: {FITTED_PARAMS_FILE} not found")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _build_schedules(start_date, num_days):
    _h = max(num_days + 14, 370)
    _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
    _mob = json.dumps(np.ones((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    _vax = json.dumps(np.zeros((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    return SimpleNamespace(
        absolute_humidity_df=pd.DataFrame({"date": _dates, "absolute_humidity": [0.01] * _h}),
        school_work_calendar_df=pd.DataFrame({"date": _dates, "is_school_day": [1.0] * _h, "is_work_day": [1.0] * _h}),
        mobility_df=pd.DataFrame({"day_of_week": ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"], "mobility_modifier": [_mob]*7}),
        daily_vaccines_df=pd.DataFrame({"date": _dates, "daily_vaccines": [_vax] * _h}),
    )


def build_model(cfg, param_overrides, rep, subpop_overrides=None):
    # subpop_overrides: list of {param: value} indexed by subpop order (metapop only)
    _cfg = copy.deepcopy(cfg)
    if param_overrides:
        _cfg["params"] = {**_cfg.get("params", {}), **param_overrides}
    _sched = _build_schedules(START_DATE, NUM_DAYS)
    _mc = parse_model_config_from_dict(_cfg, schedules_input=_sched)
    _A, _R = NUM_AGE_GROUPS, NUM_RISK_GROUPS
    _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
    _first = _comps[0] if _comps else "S"
    _N = _cfg.get("total_population", 100000)
    _comp_init = {_first: np.full((_A, _R), float(_N))}
    for _c in _comps[1:]:
        _comp_init.setdefault(_c, np.zeros((_A, _R)))
    _state = build_state_from_config(_mc, _comp_init, epi_metric_init={})
    _params = build_params_from_config(_mc, num_age_groups=_A, num_risk_groups=_R)
    _tt = clt.TransitionTypes.BINOM if STOCHASTIC else clt.TransitionTypes.BINOM_DETERMINISTIC_NO_ROUND
    _settings = clt.SimulationSettings(
        timesteps_per_day=TIMESTEPS_PER_DAY, transition_type=_tt,
        start_real_date=START_DATE, save_daily_history=True,
    )
    _subpop = ConfigDrivenSubpopModel(
        model_config=_mc, state_init=_state, params=_params,
        simulation_settings=_settings, RNG=np.random.default_rng(rep),
        schedules_input=_sched, name="pop",
    )
    _mixing = flu.FluMixingParams(travel_proportions=np.array([[1.0]]), num_locations=1)
    return ConfigDrivenMetapopModel({"pop": _subpop}, mixing_params=_mixing)


all_results = {}
for scenario_name, overrides in SCENARIOS.items():
    print(f"Running scenario: {scenario_name}")
    _sp_overrides = SUBPOP_PARAM_OVERRIDES.get(scenario_name)
    _reps_data = []
    for _rep in range(NUM_REPS):
        _m = build_model(config_dict, overrides, _rep, subpop_overrides=_sp_overrides)
        _m.simulate_until_day(NUM_DAYS)
        _sps = list(_m.subpop_models.values())
        _h = {}
        for _sp in _sps:
            for _c, _comp in _sp.compartments.items():
                _arr = np.array(_comp.history_vals_list).sum(axis=(1, 2))
                _h[_c] = _h.get(_c, 0) + _arr
        _reps_data.append(_h)
    all_results[scenario_name] = _reps_data

_db = OUTPUT_DIR / "results.db"
_con = sqlite3.connect(_db)
_cur = _con.cursor()
_cur.execute(
    "CREATE TABLE IF NOT EXISTS results "
    "(scenario TEXT, rep INTEGER, compartment TEXT, day INTEGER, value REAL)"
)
for _scen, _reps_data in all_results.items():
    for _ri, _h in enumerate(_reps_data):
        for _c, _arr in _h.items():
            _cur.executemany(
                "INSERT INTO results VALUES (?,?,?,?,?)",
                [(_scen, _ri, _c, _d + 1, float(_v)) for _d, _v in enumerate(_arr)],
            )
_con.commit()
_con.close()
print(f"Results saved to {_db}")
"""

    _scen_lines = [
        "# Define scenarios: {name: {param: value}}",
        "SCENARIOS = {",
        '    "baseline": {},',
    ]
    _subpop_lines = [
        "# Per-subpopulation parameter overrides per scenario (metapop only)",
        "# Format: {scenario_name: [override_dict_or_None, ...]} indexed by subpop order",
        "SUBPOP_PARAM_OVERRIDES = {",
    ]
    for _scen_tuple in analysis_scenarios:
        _sn, _ov = _scen_tuple[0], _scen_tuple[1]
        _sp_list = _scen_tuple[2] if len(_scen_tuple) > 2 else None
        if _ov and _sn != "baseline":
            _inner = ", ".join(f'"{_k}": {repr(_v)}' for _k, _v in _ov.items())
            _scen_lines.append(f"    {repr(_sn)}: {{{_inner}}},")
        if _sp_list and any(_r for _r in _sp_list):
            _subpop_lines.append(f"    {repr(_sn)}: {repr(_sp_list)},")
    _scen_lines.append("}")
    _subpop_lines.append("}")
    _scenarios_block = "\n".join(_scen_lines)
    _subpop_block = "\n".join(_subpop_lines)

    _script = _script.replace("# <<<SCENARIOS_BLOCK>>>", _scenarios_block).replace(
        "# <<<SUBPOP_OVERRIDES_BLOCK>>>", _subpop_block,
    ).replace(
        "NUM_DAYS = 100\n",
        f"NUM_DAYS = {int(sim_days.value)}\n",
    ).replace(
        "NUM_REPS = 1\n",
        f"NUM_REPS = {int(n_reps.value)}\n",
    ).replace(
        "STOCHASTIC = False\n",
        f"STOCHASTIC = {sim_mode.value == 'Stochastic'}\n",
    ).replace(
        "TIMESTEPS_PER_DAY = 7\n",
        f"TIMESTEPS_PER_DAY = {int(timesteps.value)}\n",
    ).replace(
        'START_DATE = "2024-01-01"\n',
        f'START_DATE = "{start_date_input.value}"\n',
    ).replace(
        "NUM_AGE_GROUPS = 1\n",
        f"NUM_AGE_GROUPS = {num_age_groups}\n",
    ).replace(
        "NUM_RISK_GROUPS = 1\n",
        f"NUM_RISK_GROUPS = {num_risk_groups}\n",
    )

    _config_dl = mo.download(
        data=_config_str.encode(), filename="model_config.json",
        label="Download model_config.json", mimetype="application/json",
    )
    _script_dl = mo.download(
        data=_script.encode(), filename="run_simulation.py",
        label="Download run_simulation.py", mimetype="text/x-python",
    )
    _fitted_dl = mo.download(
        data=_fitted_str.encode(), filename="fitted_params.json",
        label="Download fitted_params.json", mimetype="application/json",
    )
    _n_analysis = len(analysis_scenarios)
    _n_sp_overrides = sum(
        1 for _t in analysis_scenarios
        if len(_t) > 2 and _t[2] and any(_r for _r in _t[2])
    )
    if _n_analysis:
        _sp_note_extra = (
            f" `SUBPOP_PARAM_OVERRIDES` includes **{_n_sp_overrides}** scenario(s) with per-subpop overrides."
            if _n_sp_overrides else ""
        )
        _scen_note = mo.callout(
            mo.md(
                f"`SCENARIOS` pre-populated from the Analysis tab "
                f"(**{_n_analysis}** scenario(s) + baseline). "
                f"Edit the script to add or change scenarios.{_sp_note_extra}"
            ),
            kind="info",
        )
    else:
        _scen_note = mo.callout(
            mo.md(
                "No Analysis scenarios defined — only `baseline` is included in `SCENARIOS`. "
                "Define scenarios in the Analysis tab to pre-populate this block."
            ),
            kind="info",
        )

    _how_to = mo.callout(
        mo.md(
            "**How to run**\n\n"
            "1. Download `run_simulation.py`, `model_config.json`, and "
            "`fitted_params.json` below into one folder.\n"
            "2. (Optional) edit the `SCENARIOS` block and top constants in the script.\n"
            "3. Run `python run_simulation.py` — results are written to a "
            "`simulation_output/` folder alongside the script."
        ),
        kind="info",
    )
    mo.vstack([
        mo.Html(
            f'<div style="font-size:1.35rem;font-weight:800;color:{_ACC};">Export</div>'
            '<div style="color:#777;margin:.1rem 0 .2rem;">Generate a standalone '
            "script to run this model outside the notebook.</div>"
        ),
        section_card(
            step_header("①", "Generated script",
                        "A runnable run_simulation.py — edit SCENARIOS and the top "
                        "constants before running.",
                        accent=_ACC),
            mo.vstack([
                _how_to,
                _scen_note,
                mo.accordion({"run_simulation.py": mo.md(f"```python\n{_script}\n```")}),
            ]),
            accent=_ACC,
        ),
        section_card(
            step_header("②", "Downloads",
                        "Grab the script and its input files.", accent=_ACC),
            mo.vstack([
                mo.hstack([_config_dl, _script_dl, _fitted_dl], justify="start"),
                mo.md(f"*Outputs auto-saved to `{output_dir}/`*"),
            ]),
            accent=_ACC,
        ),
    ])
    return


# ============================================================
# Analysis tab — sub-tab selector (must depend only on mo)
# ============================================================

