# _nb_export.py
# Section: Export tab cell
# Part of model_builder_notebook.py — assembled by build_notebook.py

@app.cell
def _export_display(config_dict, fit_result, analysis_use_fitted, analysis_fitted_full, output_dir, json, mo, main_tab, num_age_groups, num_risk_groups, analysis_sim_days, analysis_stochastic, analysis_n_reps, analysis_timesteps, analysis_uncertainty_source, analysis_n_param_sets, analysis_n_param_sets_avail, rng_seed, start_date_input, analysis_scenarios, is_metapop, metapop_folder_input, metapop_travel_config, step_header, section_card, CLT_ACCENT, loaded_schedule_dfs):
    mo.stop(main_tab.value != "Export", None)
    _ACC = CLT_ACCENT["export"]
    _config_str = json.dumps(config_dict, indent=2)
    # Full (unexpanded) structure — best_params, scale_groups, num_days,
    # tv_knot_spacing_days — so run_simulation.py can reproduce seed_scale_*
    # and m(t) itself, not just the flattened scalar overrides used in-notebook.
    # Reflects whichever fitted-params source is active in the Analysis tab.
    if analysis_use_fitted.value and analysis_fitted_full:
        _fitted_str = json.dumps(analysis_fitted_full, indent=2)
    elif fit_result is not None:
        _fitted_str = json.dumps({
            "best_params": fit_result.best_params,
            "num_days": fit_result.num_days,
            "method": fit_result.method,
            "accepted_params": fit_result.accepted_params,
            "scale_groups": fit_result.scale_groups,
            "tv_knot_spacing_days": fit_result.tv_knot_spacing_days,
        }, indent=2)
    else:
        _fitted_str = json.dumps({}, indent=2)

    _script = """\
    #!/usr/bin/env python3
    \"\"\"
    Generated by CLT Model Builder Notebook.
    Usage: python run_simulation.py

    Location: this file must sit exactly two directory levels below the
    repo root that contains generic_core/, clt_toolkit/ and flu_core/ —
    e.g. <repo_root>/some_folder/some_subfolder/run_simulation.py — since
    it adds Path(__file__).parent.parent.parent to sys.path to import
    them. model_config.json (and fitted_params.json, if used) must sit
    alongside it in that same directory.
    If you move this file, update the sys.path.insert(...) line below:
    count how many directories separate this file from the repo root,
    then use that many + 1 .parent calls from __file__ (equivalently,
    .parent calls on _HERE equal to that count). Also make sure
    model_config.json / fitted_params.json are still next to this file.
    \"\"\"

    import sys
    import io
    import os
    import json
    import copy
    import itertools
    import numpy as np
    import pandas as pd
    import sqlite3
    from pathlib import Path
    from types import SimpleNamespace
    from concurrent.futures import ProcessPoolExecutor, as_completed

    # ---- Configurable ----
    MODEL_CONFIG_FILE = "model_config.json"
    FITTED_PARAMS_FILE = "fitted_params.json"  # set to None to skip
    # Real uploaded schedule CSVs (humidity / school-work calendar / mobility /
    # vaccination), single-population only. Without this file the script falls
    # back to flat constants (no seasonal forcing, NO vaccination), which is a
    # materially different model than the one built in the notebook. Set to None
    # only if the model genuinely has no such inputs.
    SCHEDULES_FILE = "schedules.json"
    # Transition variables (daily flows, e.g. I_to_H / IV_to_H) to record
    # alongside the compartments. None = every transition in model_config.json;
    # set to a list to record only some, or [] for compartments only.
    TRANSITION_VARS = None
    OUTPUT_DIR = Path("simulation_output")
    NUM_DAYS = 100
    NUM_REPS = 1
    STOCHASTIC = False
    TIMESTEPS_PER_DAY = 7
    START_DATE = "2024-01-01"
    NUM_AGE_GROUPS = 1
    NUM_RISK_GROUPS = 1
    # Base RNG seed; each run uses default_rng(SEED_BASE + run_index), matching
    # the notebook's Analysis tab.
    SEED_BASE = 0
    # Scenario x replicate runs are independent, so they run in a process pool
    # (real OS processes -- CPU-bound numpy/Python simulation work would not
    # benefit from threads because of the GIL). None = os.cpu_count(); set to 1
    # to run serially (e.g. for easier debugging/tracebacks).
    NUM_WORKERS = None

    # Where the spread between replicates comes from (mirrors the Analysis tab's
    # "Uncertainty source" control):
    #   "transitions"            - every replicate uses the fitted BEST parameter
    #                              set and differs only in the transition RNG.
    #   "parameters"             - draw NUM_PARAM_SETS sets at random (without
    #                              replacement) from the fit's accepted_params and
    #                              run each ONE time with DETERMINISTIC transitions.
    #                              The spread is parameter uncertainty alone, with
    #                              no transition RNG noise, so repeating a set
    #                              would only duplicate its trajectory -- NUM_REPS
    #                              is ignored and the ensemble size is the number
    #                              of sampled sets.
    #   "parameters+transitions" - draw NUM_PARAM_SETS sets at random (without
    #                              replacement) from the fit's accepted_params and
    #                              spread NUM_REPS replicates evenly across them,
    #                              so the ensemble carries parameter uncertainty
    #                              too.
    # Both sampling modes require a fitted_params.json with more than one accepted
    # set, and both are ignored when STOCHASTIC is False (deterministic always runs
    # once, with the best set).
    UNCERTAINTY_SOURCE = "transitions"
    NUM_PARAM_SETS = 1
    # Whether the transition engine itself is stochastic. Derived, not a setting:
    # the "parameters" mode is stochastic in the sense that it samples the
    # posterior, but each run's transitions are deterministic.
    RUN_STOCHASTIC = STOCHASTIC and UNCERTAINTY_SOURCE != "parameters"

    # <<<METAPOP_BLOCK>>>

    # <<<SCENARIOS_BLOCK>>>

    # <<<SUBPOP_OVERRIDES_BLOCK>>>

    # <<<DESIGNED_PARAMS_BLOCK>>>

    # <<<DESIGNED_PARAM_RATIOS_BLOCK>>>

    # <<<DOSE_MULTIPLIER_BLOCK>>>

    # <<<DOSE_MULTIPLIER_SUBPOP_BLOCK>>>

    # ---- Setup ----
    _HERE = Path(__file__).parent
    sys.path.insert(0, str(_HERE.parent.parent))

    import clt_toolkit as clt
    import flu_core as flu
    from generic_core.config_parser import parse_model_config_from_dict
    from generic_core.generic_model import (
        ConfigDrivenSubpopModel, build_state_from_config, build_params_from_config,
    )
    from generic_core.generic_metapop import ConfigDrivenMetapopModel
    from generic_core.model_factory import (
        build_compartment_init, make_metapop_from_folder, extract_history,
        extract_history_full, scale_dose_schedule_df, config_schedule_df_attributes,
    )
    from generic_core.fitting import (
        _scale_compartment_init, _inject_tv_transmission, _tv_knot_days,
        build_transmission_multiplier_array, prepare_param_sets,
    )

    with open(_HERE / MODEL_CONFIG_FILE) as _f:
        config_dict = json.load(_f)

    if TRANSITION_VARS is None:
        TRANSITION_VARS = [
            _t["name"] for _t in config_dict.get("transitions", []) if _t.get("name")
        ]
    else:
        TRANSITION_VARS = list(TRANSITION_VARS)

    # Fitted params can carry three kinds of entries:
    #  - regular config["params"] scalars/arrays  -> merged in directly below
    #  - seed_scale_<comp>  -> scales that seeded compartment's initial condition
    #    (mirrors generic_core.fitting._scale_compartment_init); applied in
    #    build_model(), not a config["params"] entry
    #  - m_dlog_*  -> log-increments of the fitted time-varying transmission
    #    multiplier m(t); reconstructed in build_model() via a
    #    'transmission_multiplier' schedule (mirrors
    #    generic_core.fitting._inject_tv_transmission), exact over the fit period
    #    (FIT_NUM_DAYS) and held flat at its last value beyond it.
    #  - phi (NB2 observation-noise dispersion) and linked-scale multiplier keys
    #    (see SCALE_GROUPS) are not model parameters and are dropped/expanded.
    SEED_SCALES = {}
    TV_INCREMENTS = []
    TV_SPACING = 30
    FIT_NUM_DAYS = 0
    # Accepted/posterior parameter sets behind the best set, used only when
    # UNCERTAINTY_SOURCE samples parameters ("parameters" / "parameters+transitions").
    PARAM_SETS = []


    def _split_pset(_pset):
        # A prepared param set mixes three kinds of entry. Split them the way
        # each is actually applied: model params merge into config["params"],
        # seed_scale_* scales the initial conditions, m_dlog_* rebuilds m(t).
        # phi (NB2 observation-noise dispersion) is not a model parameter.
        _model = {
            _k: _v for _k, _v in _pset.items()
            if _k != "phi" and not _k.startswith("m_dlog_") and not _k.startswith("seed_scale_")
        }
        _scales = {
            _k[len("seed_scale_"):]: float(_v)
            for _k, _v in _pset.items() if _k.startswith("seed_scale_")
        }
        _incr = [
            _v for _, _v in sorted(
                (
                    (int(_k[len("m_dlog_"):]), float(_v))
                    for _k, _v in _pset.items()
                    if _k.startswith("m_dlog_") and _k[len("m_dlog_"):].isdigit()
                ),
                key=lambda _t: _t[0],
            )
        ]
        return _model, _scales, _incr


    if FITTED_PARAMS_FILE is not None:
        _fp = _HERE / FITTED_PARAMS_FILE
        if _fp.exists():
            with open(_fp) as _f:
                _fitted_raw = json.load(_f)
        else:
            print(f"Warning: {FITTED_PARAMS_FILE} not found")
            _fitted_raw = {}

        _best_params = _fitted_raw.get("best_params", _fitted_raw) if isinstance(_fitted_raw, dict) else {}
        _accepted = (_fitted_raw.get("accepted_params") or []) if isinstance(_fitted_raw, dict) else []
        _scale_groups = (_fitted_raw.get("scale_groups", {}) or {}) if isinstance(_fitted_raw, dict) else {}
        FIT_NUM_DAYS = int(_fitted_raw.get("num_days", 0) or 0) if isinstance(_fitted_raw, dict) else 0
        TV_SPACING = int(_fitted_raw.get("tv_knot_spacing_days", 30) or 30) if isinstance(_fitted_raw, dict) else 30

        # prepare_param_sets reassembles MCMC/ABC-SMC per-element sampler columns
        # (`pn|a0`, `pn|a1`, ... — AR/gradient record one array-valued `pn`
        # directly) and expands linked-scale multipliers into concrete
        # base-param values (base := model_config baseline × multiplier). Both
        # must be resolved against the ORIGINAL (pre-fit) config baseline, so
        # capture it before config_dict["params"] is updated below.
        _orig_params = dict(config_dict.get("params", {}) or {})
        _expanded = prepare_param_sets([_best_params], _scale_groups, _orig_params)[0]
        PARAM_SETS = prepare_param_sets(_accepted, _scale_groups, _orig_params)

        FITTED_PARAMS, SEED_SCALES, TV_INCREMENTS = _split_pset(_expanded)
        if TV_INCREMENTS and FIT_NUM_DAYS <= 0:
            print("Warning: fitted params have m_dlog_* but no num_days — m(t) will not be reconstructed")
            TV_INCREMENTS = []
        config_dict["params"] = {**config_dict.get("params", {}), **FITTED_PARAMS}

        if SEED_SCALES:
            print(f"Applying fitted seed scaling to: {sorted(SEED_SCALES)}")
        if TV_INCREMENTS:
            print(
                f"Reconstructing m(t) from {len(TV_INCREMENTS)} fitted log-increment(s) "
                f"(fit period {FIT_NUM_DAYS} days, knots every {TV_SPACING} days)"
            )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


    def _build_tvm_df(start_date, num_days, tv_increments=None):
        # Reconstruct the fitted m(t) trajectory: exact over the fit period
        # (FIT_NUM_DAYS) and held flat at its last value beyond it. Returns None
        # when no m(t) was fit. Shared by the single-pop schedules and the metapop
        # build (where it is broadcast identically to every subpop).
        # tv_increments defaults to the best set's; a sampled param set passes
        # its own (each posterior draw carries its own m(t) trajectory).
        _incr = TV_INCREMENTS if tv_increments is None else tv_increments
        if not _incr or FIT_NUM_DAYS <= 0:
            return None
        _h = max(num_days + 14, 370)
        _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
        _knots = _tv_knot_days(FIT_NUM_DAYS, TV_SPACING)
        _m_fit = build_transmission_multiplier_array(_incr, _knots, FIT_NUM_DAYS)
        if _h <= FIT_NUM_DAYS:
            _m_full = _m_fit[:_h]
        else:
            _m_full = np.concatenate([_m_fit, np.full(_h - FIT_NUM_DAYS, _m_fit[-1])])
        return pd.DataFrame({"date": _dates, "transmission_multiplier": _m_full})


    def _load_schedule_csvs():
        # The uploaded schedule CSVs, saved alongside this script by the Export
        # tab. Any attribute absent here had no CSV uploaded in the notebook and
        # correctly falls back to a flat constant below.
        if not SCHEDULES_FILE:
            return {}
        _p = _HERE / SCHEDULES_FILE
        if not _p.exists():
            print(
                f"Warning: {SCHEDULES_FILE} not found next to this script — falling back to "
                "flat constant schedules (no seasonal forcing, no vaccination). Results will "
                "NOT match the notebook. Re-download schedules.json from the Export tab."
            )
            return {}
        with open(_p) as _f:
            return json.load(_f)


    def _dose_mult_for(dose_mult, attr):
        # A scenario's dose multiplier is either
        #   - a per-age-group list  -> applied to EVERY vaccine_schedule, or
        #   - a {df_attribute: per-age-group list} dict -> per-schedule, letting
        #     two `scheduled_exact` schedules be scaled by different amounts
        #     (a schedule absent from the dict is left unscaled).
        # Both shapes are accepted so hand-edited scripts using the simple list
        # form keep working.
        if dose_mult is None:
            return None
        if isinstance(dose_mult, dict):
            return dose_mult.get(attr)
        return dose_mult


    def _build_schedules(start_date, num_days, tv_increments=None, dose_mult=None):
        # dose_mult: per-age-group multiplier on the `vaccine_schedule`-template
        # schedules (see scale_dose_schedule_df and _dose_mult_for above) -- e.g.
        # 0 to zero out an age group for a no-dose / single-age-only scenario.
        # Despite the "daily_vaccines" naming (fixed by the model config schema),
        # this isn't vaccine-specific -- it scales whatever `scheduled_exact`
        # represents (antiviral prophylaxis courses, etc.).
        _h = max(num_days + 14, 370)
        _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
        _mob = json.dumps(np.ones((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
        _vax = json.dumps(np.zeros((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
        _csvs = _load_schedule_csvs()

        def _real_or(_name, _fallback):
            if _name in _csvs:
                return pd.read_csv(io.StringIO(_csvs[_name]))
            return _fallback

        _kwargs = {}
        _tvm_df = _build_tvm_df(start_date, num_days, tv_increments)
        if _tvm_df is not None:
            _kwargs["transmission_multiplier_df"] = _tvm_df
        # Any vaccine_schedule-template schedule other than the default-named
        # "vaccinated_transfer_schedule"/"daily_vaccines" gets its df loaded (or
        # falls back to an all-zero constant) and scaled by its OWN entry in
        # dose_mult (see _dose_mult_for).
        _extra_attrs = sorted({
            _sc.get("schedule_config", {}).get("df_attribute")
            for _sc in config_dict.get("schedules", []) or []
            if _sc.get("schedule_template") == "vaccine_schedule"
            and _sc.get("schedule_config", {}).get("df_attribute") not in (None, "daily_vaccines_df")
        })
        for _attr in _extra_attrs:
            _kwargs[_attr] = scale_dose_schedule_df(_real_or(
                _attr,
                pd.DataFrame({"date": _dates, "daily_vaccines": [_vax] * _h})),
                _dose_mult_for(dose_mult, _attr))
        return SimpleNamespace(
            absolute_humidity_df=_real_or(
                "absolute_humidity_df",
                pd.DataFrame({"date": _dates, "absolute_humidity": [0.01] * _h})),
            school_work_calendar_df=_real_or(
                "school_work_calendar_df",
                pd.DataFrame({"date": _dates, "is_school_day": [1.0] * _h, "is_work_day": [1.0] * _h})),
            mobility_df=_real_or(
                "mobility_df",
                pd.DataFrame({"day_of_week": ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"], "mobility_modifier": [_mob]*7})),
            daily_vaccines_df=scale_dose_schedule_df(_real_or(
                "daily_vaccines_df",
                pd.DataFrame({"date": _dates, "daily_vaccines": [_vax] * _h})),
                _dose_mult_for(dose_mult, "daily_vaccines_df")),
            **_kwargs,
        )


    def build_model(cfg, param_overrides, rep, subpop_overrides=None,
                    seed_scales=None, tv_increments=None,
                    dose_mult=None, dose_mult_per_subpop=None):
        # subpop_overrides: list of {param: value} indexed by subpop order (metapop only)
        # seed_scales / tv_increments default to the fitted best set's; a sampled
        # param set passes its own so each run reproduces that draw's initial
        # conditions and m(t) trajectory.
        # dose_mult / dose_mult_per_subpop: per-age-group multiplier(s) on a
        # `scheduled_exact` transition's daily schedule (see
        # scale_dose_schedule_df), mirroring the Analysis tab's schedule-scaling
        # control. dose_mult applies to every subpop identically (or is the only
        # one used, single-population); dose_mult_per_subpop (metapop only) is a
        # list indexed by subpop order whose non-None entries override dose_mult
        # for that subpop.
        _seed_scales = SEED_SCALES if seed_scales is None else seed_scales
        _tv_incr = TV_INCREMENTS if tv_increments is None else tv_increments
        _cfg = copy.deepcopy(cfg)
        if param_overrides:
            _cfg["params"] = {**_cfg.get("params", {}), **param_overrides}
        if _tv_incr:
            _cfg, _ = _inject_tv_transmission(_cfg)

        if IS_METAPOP:
            # Metapop: reuse the folder-driven factory, which reads
            # metapop_config.json, per-subpop schedule CSVs, travel matrix and
            # per-subpop initial conditions. The scenario's shared overrides are
            # already merged into _cfg["params"] above (applied to every subpop);
            # subpop_overrides supplies per-subpop values. The fitted m(t) is
            # reconstructed once and broadcast identically to all subpops.
            _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
            if _seed_scales:
                print(
                    "Warning: seed-scale reproduction is not applied for metapop export "
                    "(per-subpop seeded initial conditions are read from the metapop folder); "
                    f"ignoring fitted seed scales {sorted(_seed_scales)}."
                )
            # Split the scenario's dose multiplier per schedule: the factory
            # takes the default schedule's vector as `dose_mult` and the rest
            # as an `extra_dose_mult` dict. _dose_mult_for accepts either a
            # bare per-age-group list (same scaling for every schedule) or a
            # {df_attribute: list} dict (per-schedule scaling).
            _extra_attrs = sorted(config_schedule_df_attributes(_cfg) - {"daily_vaccines_df"})
            _base_dose_mult = _dose_mult_for(dose_mult, "daily_vaccines_df")
            _extra_dose_mult = (
                {_attr: _dose_mult_for(dose_mult, _attr) for _attr in _extra_attrs}
                if (_extra_attrs and dose_mult is not None) else None
            )
            _base_dm_per_sp = _extra_dm_per_sp = None
            if dose_mult_per_subpop:
                _base_dm_per_sp = [
                    _dose_mult_for(_dm, "daily_vaccines_df") for _dm in dose_mult_per_subpop
                ]
                _extra_dm_per_sp = [
                    ({_attr: _dose_mult_for(_dm, _attr) for _attr in _extra_attrs}
                     if (_extra_attrs and _dm is not None) else None)
                    for _dm in dose_mult_per_subpop
                ]
            _m, _ = make_metapop_from_folder(
                METAPOP_FOLDER, _cfg, START_DATE, NUM_DAYS, _comps,
                seed_offset=rep, seed_base=SEED_BASE, ts_per_day=TIMESTEPS_PER_DAY,
                stochastic=RUN_STOCHASTIC, save_daily=True, tvs=TRANSITION_VARS,
                param_overrides=None,
                param_overrides_per_subpop=subpop_overrides,
                travel_config=METAPOP_TRAVEL_CONFIG or None,
                num_age_groups=NUM_AGE_GROUPS, num_risk_groups=NUM_RISK_GROUPS,
                transmission_multiplier_df=_build_tvm_df(START_DATE, NUM_DAYS, _tv_incr),
                dose_mult=_base_dose_mult, dose_mult_per_subpop=_base_dm_per_sp,
                extra_dose_mult=_extra_dose_mult, extra_dose_mult_per_subpop=_extra_dm_per_sp,
            )
            return _m

        _sched = _build_schedules(START_DATE, NUM_DAYS, _tv_incr, dose_mult)
        _mc = parse_model_config_from_dict(_cfg, schedules_input=_sched)
        _A, _R = NUM_AGE_GROUPS, NUM_RISK_GROUPS
        _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
        _first = _comps[0] if _comps else "S"
        _N = _cfg.get("total_population", 100000)
        # Seeded compartments (e.g. an initial E count) from the Builder's Step 6
        # initial-conditions table, same source Analysis/Forecast read — not just
        # everyone starting in the first compartment.
        _ic_entry = (_cfg.get("initial_conditions", {}) or {}).get("aggregate_pop", {})
        if _ic_entry:
            _pop_arr = np.asarray(_ic_entry.get("population", np.full((_A, _R), float(_N))), dtype=float)
            _seed_arrays = {
                _c: np.asarray(_a, dtype=float)
                for _c, _a in (_ic_entry.get("seeds", {}) or {}).items()
                if _c in _comps
            }
            _comp_init, _ = build_compartment_init(_seed_arrays, _pop_arr, _comps)
        else:
            _comp_init = {_first: np.full((_A, _R), float(_N))}
            for _c in _comps[1:]:
                _comp_init.setdefault(_c, np.zeros((_A, _R)))
        if _seed_scales:
            _comp_init = _scale_compartment_init(_comp_init, _seed_scales, _comps, _A, _R)
        _state = build_state_from_config(_mc, _comp_init, epi_metric_init={})
        _params = build_params_from_config(_mc, num_age_groups=_A, num_risk_groups=_R)
        _tt = clt.TransitionTypes.BINOM if RUN_STOCHASTIC else clt.TransitionTypes.BINOM_DETERMINISTIC_NO_ROUND
        _settings = clt.SimulationSettings(
            timesteps_per_day=TIMESTEPS_PER_DAY, transition_type=_tt,
            start_real_date=START_DATE, save_daily_history=True,
            transition_variables_to_save=TRANSITION_VARS,
        )
        _subpop = ConfigDrivenSubpopModel(
            model_config=_mc, state_init=_state, params=_params,
            simulation_settings=_settings, RNG=np.random.default_rng(SEED_BASE + rep),
            schedules_input=_sched, name="pop",
        )
        _mixing = flu.FluMixingParams(travel_proportions=np.array([[1.0]]), num_locations=1)
        return ConfigDrivenMetapopModel(
            subpop_models=[_subpop], mixing_params=_mixing,
            model_config=_mc, travel_config={},
        )


    # ---- Uncertainty source: which parameter set each replicate runs with ----
    # Mirrors the Analysis tab. "transitions" (and every deterministic run) uses
    # the fitted best set — already merged into config_dict["params"] and into
    # each scenario's overrides — so replicates differ only in the transition
    # RNG. Otherwise draw NUM_PARAM_SETS sets at random without replacement:
    # "parameters" runs each drawn set exactly once (transitions are
    # deterministic, so a repeated set would only duplicate its trajectory —
    # NUM_REPS is ignored), "parameters+transitions" spreads NUM_REPS replicates
    # evenly across the drawn sets (remainder distributed at random).
    _param_only = UNCERTAINTY_SOURCE == "parameters"
    _use_psets = (
        STOCHASTIC
        and UNCERTAINTY_SOURCE in ("parameters", "parameters+transitions")
        and len(PARAM_SETS) > 1
    )
    if _use_psets:
        _rng_sched = np.random.default_rng(SEED_BASE)
        _k = min(int(NUM_PARAM_SETS), len(PARAM_SETS), *(() if _param_only else (NUM_REPS,)))
        _sel = _rng_sched.choice(len(PARAM_SETS), size=_k, replace=False)
        RUN_PARAM_SETS = [PARAM_SETS[int(_i)] for _i in _sel]
        if _param_only:
            RUN_SCHEDULE = list(range(_k))
        else:
            _base_r, _extra_r = divmod(NUM_REPS, _k)
            RUN_SCHEDULE = [_i for _i in range(_k) for _ in range(_base_r)]
            if _extra_r:
                RUN_SCHEDULE += [int(_i) for _i in _rng_sched.choice(_k, size=_extra_r, replace=False)]
        if __name__ == "__main__":
            # This module-level block runs again on import in every worker
            # process (spawn re-imports the script as __main__; fork re-runs
            # it too under some pool implementations) since RUN_PARAM_SETS/
            # RUN_SCHEDULE must exist there for _apply_pset. Only print once,
            # in the parent.
            print(
                f"Parameter uncertainty: {_k} set(s) sampled from {len(PARAM_SETS)} accepted, "
                f"{len(RUN_SCHEDULE)} run(s) per scenario"
                + (" (deterministic transitions)" if _param_only else "")
            )
    else:
        if (
            __name__ == "__main__"
            and UNCERTAINTY_SOURCE in ("parameters", "parameters+transitions")
            and STOCHASTIC
        ):
            _fallback = (
                "a single deterministic run of the best parameter set"
                if _param_only
                else "transition-only uncertainty with the best parameter set"
            )
            print(
                f"Warning: UNCERTAINTY_SOURCE is '{UNCERTAINTY_SOURCE}' but "
                f"{FITTED_PARAMS_FILE} has fewer than 2 accepted_params — falling back "
                f"to {_fallback}."
            )
        RUN_PARAM_SETS = []
        RUN_SCHEDULE = [None] * (NUM_REPS if RUN_STOCHASTIC else 1)


    def _apply_pset(overrides, pset_idx, designed, ratios=None):
        # Layer a sampled param set under the scenario's overrides: the set
        # supplies every fitted param the scenario design did not deliberately
        # set (DESIGNED_PARAMS), so the ensemble carries parameter uncertainty
        # without undoing the sweep or the edited scenario values. Returns the
        # (param_overrides, seed_scales, tv_increments) triple for this run.
        # A designed param with a known ratio in DESIGNED_PARAM_RATIOS (the
        # scenario's override / catalog baseline at export time) instead has
        # that ratio applied to the sampled draw's own value, so the
        # scenario's scaling factor carries through posterior uncertainty
        # rather than pinning one absolute value across every draw.
        if pset_idx is None:
            return overrides, None, None
        _model, _scales, _incr = _split_pset(RUN_PARAM_SETS[pset_idx])
        _ov = dict(overrides or {})
        _ratios = ratios or {}
        for _k2, _v2 in _model.items():
            if _k2 in designed:
                _ratio = _ratios.get(_k2)
                if _ratio is None:
                    continue
                if isinstance(_ratio, list):
                    _ov[_k2] = (np.asarray(_ratio, dtype=float) * np.asarray(_v2, dtype=float)).tolist()
                else:
                    _ov[_k2] = float(_ratio) * float(_v2)
                continue
            _ov[_k2] = _v2
        return _ov, _scales, _incr


    def _run_one(scenario_name, overrides, designed, dose_mult, dose_mult_per_subpop,
                 ratios, sp_overrides, rep, pset_idx):
        # One (scenario, replicate) unit of work -- everything a pool worker
        # needs is passed in as plain, picklable arguments; module globals
        # used inside (config_dict, NUM_DAYS, TRANSITION_VARS, RUN_PARAM_SETS
        # via _apply_pset, ...) are rebuilt identically in every worker
        # process when it re-imports this script, so they don't need to be
        # passed explicitly.
        _run_ov, _run_scales, _run_incr = _apply_pset(overrides, pset_idx, designed, ratios)
        _m = build_model(
            config_dict, _run_ov, rep, subpop_overrides=sp_overrides,
            seed_scales=_run_scales, tv_increments=_run_incr,
            dose_mult=dose_mult, dose_mult_per_subpop=dose_mult_per_subpop,
        )
        _m.simulate_until_day(NUM_DAYS)
        _sps = list(_m.subpop_models.values())
        _comp_names = list(_sps[0].compartments.keys())
        # extract_history sums over age/risk and subpops, and — critically —
        # aggregates transition variables from per-sub-timestep to per-day.
        # Transition history is saved once per sub-timestep, so summing it
        # raw would give a series TIMESTEPS_PER_DAY x too long and each
        # value TIMESTEPS_PER_DAY x too small.
        _h = extract_history(_m, _comp_names, tvs=TRANSITION_VARS)
        # Fully-resolved companion to _h -- same compartments/transitions,
        # but per-subpop (day, age_group, risk_group) arrays instead of
        # (day,) scalars summed over subpop/age/risk. Needed by anything
        # that cares which subpop/age/risk group a flow happened in (e.g.
        # per-age-group vaccination-impact tables); extract_history's own
        # summed totals stay the fast path for the population aggregate.
        _h_full = extract_history_full(_m, _comp_names, tvs=TRANSITION_VARS)
        _kinds = {_k: ("transition" if _k in TRANSITION_VARS else "compartment") for _k in _h}
        return scenario_name, rep, pset_idx, _h, _h_full, _kinds


    # ---- Everything below only runs in the parent process. ----
    # Guarding it is required (not just tidy) on spawn-based multiprocessing
    # (the default on macOS and Windows): each pool worker re-imports this
    # file as __main__, so without this guard every worker would recursively
    # try to build its own pool and re-run the whole scenario sweep. Under
    # fork-based multiprocessing (Linux's default) it isn't strictly
    # required, but keeping it makes the script behave identically on all
    # three platforms.
    if __name__ == "__main__":
        _tasks = []
        for scenario_name, overrides in SCENARIOS.items():
            _sp_overrides = SUBPOP_PARAM_OVERRIDES.get(scenario_name)
            # A scenario absent from DESIGNED_PARAMS was added by hand, so
            # nothing says which of its params are deliberate — protect all
            # of them rather than silently letting a sampled set overwrite
            # the values the user just wrote. An explicit (possibly empty)
            # list always wins.
            if scenario_name in DESIGNED_PARAMS:
                _designed = set(DESIGNED_PARAMS[scenario_name])
            else:
                _designed = set(overrides or {})
            _dose_mult = DOSE_MULTIPLIER.get(scenario_name)
            _dose_mult_per_subpop = DOSE_MULTIPLIER_PER_SUBPOP.get(scenario_name)
            _ratios = DESIGNED_PARAM_RATIOS.get(scenario_name, {})
            # Seed by position in the run schedule so every run gets a
            # distinct RNG stream once replicates are spread across
            # parameter sets.
            for _rep, _pset_idx in enumerate(RUN_SCHEDULE):
                _tasks.append((
                    scenario_name, overrides, _designed, _dose_mult,
                    _dose_mult_per_subpop, _ratios, _sp_overrides, _rep, _pset_idx,
                ))

        _n_workers = NUM_WORKERS or os.cpu_count() or 1
        _n_workers = min(_n_workers, len(_tasks)) or 1
        print(f"Running {len(_tasks)} simulation(s) across {_n_workers} worker process(es)")

        all_results = {_scen: [] for _scen in SCENARIOS}
        if _n_workers == 1:
            # Serial fallback (NUM_WORKERS = 1) -- also handy for debugging,
            # since a worker-process traceback is otherwise harder to inspect.
            for _t in _tasks:
                _scen, _rep, _psi, _h, _h_full, _kinds = _run_one(*_t)
                all_results[_scen].append((_rep, _h, _h_full, _kinds, _psi))
        else:
            with ProcessPoolExecutor(max_workers=_n_workers) as _ex:
                _futures = {_ex.submit(_run_one, *_t): _t for _t in _tasks}
                for _fut in as_completed(_futures):
                    _scen_name = _futures[_fut][0]
                    _scen, _rep, _psi, _h, _h_full, _kinds = _fut.result()
                    print(f"Finished scenario={_scen_name} rep={_rep}")
                    all_results[_scen].append((_rep, _h, _h_full, _kinds, _psi))

        # Pool completion order is nondeterministic; sort each scenario's
        # replicates back into run-schedule order so the `rep` column
        # written to results.db below matches what a serial run would have
        # produced.
        for _scen in all_results:
            all_results[_scen] = [
                (_h, _h_full, _kinds, _psi)
                for (_rep, _h, _h_full, _kinds, _psi) in sorted(all_results[_scen], key=lambda _r: _r[0])
            ]

        _db = OUTPUT_DIR / "results.db"
        _con = sqlite3.connect(_db)
        # Unlike a from-scratch batch script, this results.db is appended to
        # across export runs (see the column check below), so a full
        # durability trade-off (synchronous=OFF) risks corrupting rows from
        # earlier runs too, not just this one. WAL + synchronous=NORMAL is
        # the standard safer middle ground -- it skips most of the per-write
        # fsync cost (the dominant cost for stochastic runs with hundreds of
        # replicates x days x age/risk groups) while staying safe against an
        # application crash; only a concurrent OS crash/power loss could
        # still corrupt data.
        _con.execute("PRAGMA journal_mode = WAL")
        _con.execute("PRAGMA synchronous = NORMAL")
        _cur = _con.cursor()
        # `compartment` keeps its name (so existing queries still work) but now holds
        # transition-variable names too; `kind` distinguishes them. `param_set` is the
        # index into the sampled parameter sets (NULL when parameter uncertainty is
        # off), so replicates can be grouped by draw. A results.db from an older
        # export lacks these columns, so fail loudly rather than silently dropping the
        # new rows or corrupting the old table.
        _existing = _cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='results'"
        ).fetchone()
        if _existing:
            _cols = {_r[1] for _r in _cur.execute("PRAGMA table_info(results)")}
            _missing = {"kind", "param_set"} - _cols
            if _missing:
                _con.close()
                raise SystemExit(
                    f"{_db} was written by an older version of this script (missing "
                    f"column(s): {sorted(_missing)}). Delete or rename it and re-run."
                )
        _cur.execute(
            "CREATE TABLE IF NOT EXISTS results "
            "(scenario TEXT, rep INTEGER, param_set INTEGER, compartment TEXT, kind TEXT, "
            "day INTEGER, value REAL)"
        )
        # Same shape as `results`, plus `subpop`/`age_group`/`risk_group` columns
        # (age_group/risk_group are 0-based indices into NUM_AGE_GROUPS/
        # NUM_RISK_GROUPS) -- kept as a separate table rather than adding
        # nullable columns to `results`, so `results` alone still answers
        # population-aggregate queries without a GROUP BY. Single-population,
        # single-risk-group models (the common case) just get one subpop name
        # and risk_group=0 throughout -- still queryable the same way, just with
        # nothing to GROUP BY away.
        _cur.execute(
            "CREATE TABLE IF NOT EXISTS results_full "
            "(scenario TEXT, rep INTEGER, param_set INTEGER, compartment TEXT, kind TEXT, "
            "subpop TEXT, age_group INTEGER, risk_group INTEGER, day INTEGER, value REAL)"
        )
        print(f"Writing results for {len(all_results)} scenario(s) to {_db}")
        for _si, (_scen, _reps_data) in enumerate(all_results.items(), start=1):
            _n_reps = len(_reps_data)
            for _ri, (_h, _h_full, _kinds, _psi) in enumerate(_reps_data):
                for _c, _arr in _h.items():
                    _cur.executemany(
                        "INSERT INTO results VALUES (?,?,?,?,?,?,?)",
                        [(_scen, _ri, _psi, _c, _kinds[_c], _d + 1, float(_v))
                         for _d, _v in enumerate(_arr)],
                    )
                for _c, _sp_map in _h_full.items():
                    for _spname, _arr_full in _sp_map.items():
                        # Vectorized index construction (numpy) instead of a
                        # triple-nested Python for-loop over day/age_group/
                        # risk_group -- meaningfully faster once that product
                        # runs into the hundreds of thousands of rows across
                        # many stochastic replicates.
                        _d_idx, _a_idx, _r_idx = np.indices(_arr_full.shape)
                        _cur.executemany(
                            "INSERT INTO results_full VALUES (?,?,?,?,?,?,?,?,?,?)",
                            zip(
                                itertools.repeat(_scen), itertools.repeat(_ri), itertools.repeat(_psi),
                                itertools.repeat(_c), itertools.repeat(_kinds[_c]), itertools.repeat(_spname),
                                _a_idx.ravel().tolist(), _r_idx.ravel().tolist(),
                                (_d_idx.ravel() + 1).tolist(), _arr_full.ravel().astype(float).tolist(),
                            ),
                        )
                # Progress within a scenario's replicates, so a long
                # stochastic run (hundreds of reps) doesn't look stuck
                # between per-scenario lines below.
                if _n_reps > 20 and (_ri + 1) % 20 == 0:
                    print(f"  [{_si}/{len(all_results)}] {_scen}: wrote {_ri + 1}/{_n_reps} replicate(s)")
            print(f"[{_si}/{len(all_results)}] {_scen}: wrote {_n_reps} replicate(s) to {_db}")
        # Downstream table-building scripts filter on (scenario, compartment)
        # for every table they build, often re-querying the same scenario
        # several times -- without this index each of those is a full
        # sequential scan, which gets very slow once replicates/parameter
        # sets push `results_full` into the hundreds of millions of rows.
        _cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_results_full_scenario_compartment "
            "ON results_full (scenario, compartment)"
        )
        _cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_results_scenario_compartment "
            "ON results (scenario, compartment)"
        )
        _con.commit()
        _con.close()
        print(f"Results saved to {_db}")
"""

    _scen_lines = [
        "# Define scenarios: {name: {param: value}}",
        "#",
        "# Scalar params take a number. Array params (per age/risk group) take the",
        "# FULL nested list, shape [num_age_groups][num_risk_groups] -- the values",
        "# below are written out in full, so unlike the notebook's Analysis tab",
        "# (which only offers one uniform 'xscale' factor per scenario) you can set",
        "# each element independently by editing the literal:",
        "#",
        "#     \"uniform_x2\":  {\"I_to_H_prop\": [[0.02], [0.02], [0.02]]},",
        "#     \"worse_in_65+\": {\"I_to_H_prop\": [[0.01], [0.02], [0.20]]},",
        "#",
        "# Any param you set here must also be listed in DESIGNED_PARAMS below to",
        "# survive parameter sampling -- see the note there.",
        "SCENARIOS = {",
    ]
    # The empty "baseline" (run config_dict as-is, no overrides) is injected
    # here UNLESS the user already named one of their own scenarios
    # "baseline" -- in that case their overrides are written out like any
    # other scenario below instead of being silently shadowed by this one.
    _user_has_baseline = any(_t[0] == "baseline" for _t in analysis_scenarios)
    if not _user_has_baseline:
        _scen_lines.append('    "baseline": {},')
    _subpop_lines = [
        "# Per-subpopulation parameter overrides per scenario (metapop only)",
        "# Format: {scenario_name: [override_dict_or_None, ...]} indexed by subpop order",
        "SUBPOP_PARAM_OVERRIDES = {",
    ]
    _dose_mult_lines = [
        "# Per-age-group multiplier on a `scheduled_exact` transition's daily",
        "# schedule, per scenario (a schedule override, not a params entry).",
        "# Despite the \"vaccine\" naming baked into the model config schema",
        "# (daily_vaccines_df), scheduled_exact isn't vaccine-specific -- this",
        "# scales whatever it represents (antiviral courses, etc.). Applies to",
        "# every subpop identically in a metapop run, except where overridden by",
        "# DOSE_MULTIPLIER_PER_SUBPOP below.",
        "# Format: {scenario_name: [multiplier_per_age_group, ...]}  -- applies the",
        "# same scaling to every vaccine_schedule in the config; or, to scale two",
        "# `scheduled_exact` schedules by different amounts, a per-schedule dict:",
        "#   {scenario_name: {\"daily_vaccines_df\": [...], \"<other>_df\": [...]}}",
        "# keyed by each schedule's df_attribute (a schedule left out is unscaled).",
        "DOSE_MULTIPLIER = {",
    ]
    _dose_mult_subpop_lines = [
        "# Per-subpopulation override of DOSE_MULTIPLIER above (metapop only).",
        "# Format: {scenario_name: [multiplier_or_None, ...]} indexed by subpop",
        "# order; a None entry falls back to DOSE_MULTIPLIER. Each non-None entry",
        "# takes either shape accepted by DOSE_MULTIPLIER (list, or per-schedule",
        "# dict keyed by df_attribute).",
        "DOSE_MULTIPLIER_PER_SUBPOP = {",
    ]
    for _scen_tuple in analysis_scenarios:
        _sn, _ov = _scen_tuple[0], _scen_tuple[1]
        _sp_list = _scen_tuple[2] if len(_scen_tuple) > 2 else None
        _dm = _scen_tuple[4] if len(_scen_tuple) > 4 else None
        _dm_sp = _scen_tuple[5] if len(_scen_tuple) > 5 else None
        if _ov:
            _inner = ", ".join(f'"{_k}": {repr(_v)}' for _k, _v in _ov.items())
            _scen_lines.append(f"    {repr(_sn)}: {{{_inner}}},")
        if _sp_list and any(_r for _r in _sp_list):
            _subpop_lines.append(f"    {repr(_sn)}: {repr(_sp_list)},")
        # Scenario dose multipliers are {df_attribute: vector} dicts. When a
        # scenario only scales the default schedule (the common case) emit the
        # plain vector instead, so single-schedule exports stay in the simpler
        # historical format; the generated _dose_mult_for reads both.
        def _dm_repr(_d):
            if isinstance(_d, dict) and set(_d) == {"daily_vaccines_df"}:
                return repr(_d["daily_vaccines_df"])
            return repr(_d)

        if _dm is not None:
            _dose_mult_lines.append(f"    {repr(_sn)}: {_dm_repr(_dm)},")
        if _dm_sp is not None:
            _dose_mult_subpop_lines.append(
                f"    {repr(_sn)}: [{', '.join(_dm_repr(_x) for _x in _dm_sp)}],"
            )
    _scen_lines.append("}")
    _subpop_lines.append("}")
    _dose_mult_lines.append("}")
    _dose_mult_subpop_lines.append("}")
    _scenarios_block = "\n".join(_scen_lines)
    _subpop_block = "\n".join(_subpop_lines)
    _dose_mult_block = "\n".join(_dose_mult_lines)
    _dose_mult_subpop_block = "\n".join(_dose_mult_subpop_lines)

    # Params each scenario deliberately set (the swept param in Sensitivity, or a
    # scenario cell edited away from the baseline). A sampled parameter set
    # overrides everything EXCEPT these, so parameter uncertainty never undoes
    # the scenario design — same rule the Analysis tab applies.
    _designed_lines = [
        "# Parameters each scenario deliberately sets: {scenario_name: [param, ...]}.",
        "#",
        "# Only relevant when UNCERTAINTY_SOURCE samples parameters. Each run",
        "# takes its parameters from a sampled fitted set, EXCEPT the ones listed here",
        "# for that scenario, which keep the value given in SCENARIOS. Without this,",
        "# the sampled set would overwrite the very parameter the scenario varies and",
        "# every scenario would collapse to the same thing.",
        "#",
        "# A parameter that is in SCENARIOS but NOT in this list for that scenario is",
        "# deliberately NOT protected: it comes from the sampled parameter set, and the",
        "# SCENARIOS value is ignored. That is what makes the non-varied parameters",
        "# carry posterior uncertainty. The notebook lists exactly the parameters you",
        "# changed away from the fitted baseline, so its scenarios behave as designed.",
        "#",
        "# If you ADD a scenario by hand, add it here too. A scenario name missing from",
        "# this dict falls back to protecting everything it sets in SCENARIOS (safe for",
        "# hand-written scenarios, but it means none of its params carry parameter",
        "# uncertainty). Use an explicit empty list to opt a scenario fully into",
        "# sampling.",
        "DESIGNED_PARAMS = {",
    ]
    for _scen_tuple in analysis_scenarios:
        _sn_d, _ov_d = _scen_tuple[0], _scen_tuple[1]
        if not _ov_d:
            continue
        _dn = _scen_tuple[3] if len(_scen_tuple) > 3 else set()
        _designed_lines.append(f"    {repr(_sn_d)}: {repr(sorted(_dn))},")
    _designed_lines.append("}")
    _designed_block = "\n".join(_designed_lines)

    # Ratio (override / catalog baseline, computed when the scenario was
    # built) for each designed param, where known. Only relevant when
    # UNCERTAINTY_SOURCE samples parameters: instead of pinning the designed
    # param to the literal SCENARIOS value on every draw, _apply_pset
    # multiplies the sampled draw's own value for that param by this ratio,
    # so a scenario meant as "baseline x k" (or "baseline with this age
    # profile scaled by k") stays "sampled draw x k" under posterior
    # uncertainty instead of collapsing every draw to one fixed number. A
    # designed param absent here (or here with no ratio available -- e.g. a
    # zero catalog baseline) falls back to the old pin-to-literal-value
    # behavior.
    _ratios_lines = [
        "# Ratio (override / catalog baseline) for designed params, where known:",
        "# {scenario_name: {param: ratio_or_nested_list}}.",
        "#",
        "# Only relevant when UNCERTAINTY_SOURCE samples parameters. A designed",
        "# param listed here has the sampled draw's own value scaled by this ratio",
        "# instead of being pinned to the literal value in SCENARIOS -- so the",
        "# scenario's intended scaling survives parameter uncertainty. A designed",
        "# param NOT listed here (or added by hand) falls back to being pinned to",
        "# the literal SCENARIOS value on every draw.",
        "DESIGNED_PARAM_RATIOS = {",
    ]
    for _scen_tuple in analysis_scenarios:
        _sn_r, _ov_r = _scen_tuple[0], _scen_tuple[1]
        if not _ov_r:
            continue
        _rn = _scen_tuple[6] if len(_scen_tuple) > 6 else {}
        if _rn:
            _ratios_lines.append(f"    {repr(_sn_r)}: {repr(_rn)},")
    _ratios_lines.append("}")
    _ratios_block = "\n".join(_ratios_lines)

    # Metapopulation context. The exported script reads the metapop input folder
    # (metapop_config.json, per-subpop schedule CSVs / initial conditions, travel
    # matrix) by path at run time — it is NOT bundled into the download, so the
    # folder must be present (or edit METAPOP_FOLDER) when running the script.
    _metapop_lines = [
        "# Metapopulation reproduction (set by the notebook). When IS_METAPOP is",
        "# True the script builds the model from METAPOP_FOLDER's inputs; that",
        "# folder must exist at run time (edit the path below if you move it).",
        f"IS_METAPOP = {bool(is_metapop and metapop_folder_input.value.strip())}",
        f"METAPOP_FOLDER = {repr(metapop_folder_input.value.strip())}",
        f"METAPOP_TRAVEL_CONFIG = {repr(metapop_travel_config or {})}",
    ]
    _metapop_block = "\n".join(_metapop_lines)

    # The template literal is written indented (it lives inside this cell's
    # function body), so it must be dedented before it is a valid Python file —
    # otherwise every exported run_simulation.py fails with IndentationError on
    # its first statement. Dedent BEFORE the block substitutions below, since
    # those blocks are built at column 0 and would defeat the common-prefix
    # calculation textwrap.dedent relies on.
    import textwrap as _textwrap
    _script = _textwrap.dedent(_script)

    # Uncertainty source under the name the exported script uses. "Sampled
    # parameters only" maps to "parameters": the script draws NUM_PARAM_SETS sets
    # and runs each exactly once with deterministic transitions, so NUM_REPS is
    # meaningless there and is exported as 1 (the Analysis tab hides the replicate
    # input in that mode for the same reason).
    _export_can_sample = analysis_stochastic.value and analysis_n_param_sets_avail > 1
    _export_unc = {
        "Sampled parameters only": "parameters",
        "Sampled parameters + transitions": "parameters+transitions",
    }.get(analysis_uncertainty_source.value, "transitions") if _export_can_sample else "transitions"
    _export_reps = (
        1 if (_export_unc == "parameters" or not analysis_stochastic.value)
        else int(analysis_n_reps.value)
    )

    _script = _script.replace("# <<<METAPOP_BLOCK>>>", _metapop_block).replace(
        "# <<<SCENARIOS_BLOCK>>>", _scenarios_block,
    ).replace(
        "# <<<SUBPOP_OVERRIDES_BLOCK>>>", _subpop_block,
    ).replace(
        "# <<<DESIGNED_PARAMS_BLOCK>>>", _designed_block,
    ).replace(
        "# <<<DESIGNED_PARAM_RATIOS_BLOCK>>>", _ratios_block,
    ).replace(
        "# <<<DOSE_MULTIPLIER_BLOCK>>>", _dose_mult_block,
    ).replace(
        "# <<<DOSE_MULTIPLIER_SUBPOP_BLOCK>>>", _dose_mult_subpop_block,
    ).replace(
        # Run settings come from the Analysis tab, the same place SCENARIOS and
        # DESIGNED_PARAMS do, so the script reproduces the Analysis run as-is.
        "NUM_DAYS = 100\n",
        f"NUM_DAYS = {int(analysis_sim_days.value)}\n",
    ).replace(
        "NUM_REPS = 1\n",
        f"NUM_REPS = {_export_reps}\n",
    ).replace(
        "STOCHASTIC = False\n",
        f"STOCHASTIC = {bool(analysis_stochastic.value)}\n",
    ).replace(
        "TIMESTEPS_PER_DAY = 7\n",
        f"TIMESTEPS_PER_DAY = {int(analysis_timesteps.value)}\n",
    ).replace(
        "SEED_BASE = 0\n",
        f"SEED_BASE = {int(rng_seed.value)}\n",
    ).replace(
        'UNCERTAINTY_SOURCE = "transitions"\n',
        f'UNCERTAINTY_SOURCE = "{_export_unc}"\n',
    ).replace(
        "NUM_PARAM_SETS = 1\n",
        f"NUM_PARAM_SETS = {int(analysis_n_param_sets.value)}\n",
    ).replace(
        'START_DATE = "2024-01-01"\n',
        f'START_DATE = "{start_date_input.value}"\n',
    ).replace(
        "NUM_AGE_GROUPS = 1\n",
        f"NUM_AGE_GROUPS = {num_age_groups}\n",
    ).replace(
        "NUM_RISK_GROUPS = 1\n",
        f"NUM_RISK_GROUPS = {num_risk_groups}\n",
    )

    _config_dl = mo.download(
        data=_config_str.encode(), filename="model_config.json",
        label="Download model_config.json", mimetype="application/json",
    )
    _script_dl = mo.download(
        data=_script.encode(), filename="run_simulation.py",
        label="Download run_simulation.py", mimetype="text/x-python",
    )
    _fitted_dl = mo.download(
        data=_fitted_str.encode(), filename="fitted_params.json",
        label="Download fitted_params.json", mimetype="application/json",
    )
    # The real uploaded schedule CSVs, so run_simulation.py reproduces the
    # notebook's model instead of flat constants (mirrors the Fitting tab's
    # `schedule_csvs` field in fit_config.json). Metapop reads its own per-subpop
    # CSVs from METAPOP_FOLDER, so this is single-population only.
    _schedules_payload = {} if is_metapop else {
        _name: _df.to_csv(index=False)
        for _name, _df in (
            ("absolute_humidity_df", loaded_schedule_dfs.absolute_humidity_df),
            ("school_work_calendar_df", loaded_schedule_dfs.school_work_calendar_df),
            ("mobility_df", loaded_schedule_dfs.mobility_df),
            ("daily_vaccines_df", loaded_schedule_dfs.daily_vaccines_df),
            *(getattr(loaded_schedule_dfs, "extra_scheduled_dfs", {}) or {}).items(),
        )
        if _df is not None
    }
    _schedules_str = json.dumps(_schedules_payload, indent=2)
    _schedules_dl = mo.download(
        data=_schedules_str.encode(), filename="schedules.json",
        label="Download schedules.json", mimetype="application/json",
    )
    _n_analysis = len(analysis_scenarios)
    _n_sp_overrides = sum(
        1 for _t in analysis_scenarios
        if len(_t) > 2 and _t[2] and any(_r for _r in _t[2])
    )
    if _n_analysis:
        _sp_note_extra = (
            f" `SUBPOP_PARAM_OVERRIDES` includes **{_n_sp_overrides}** scenario(s) with per-subpop overrides."
            if _n_sp_overrides else ""
        )
        _unc_note_extra = ""
        if _export_unc != "transitions":
            _unc_note_extra = (
                f" `UNCERTAINTY_SOURCE` is set to `{_export_unc}` with "
                f"`NUM_PARAM_SETS = {int(analysis_n_param_sets.value)}` — the script samples "
                f"from `accepted_params` in `fitted_params.json` exactly as the Analysis tab "
                f"does, so **download fitted_params.json too**."
            )
            if _export_unc == "parameters":
                _unc_note_extra += (
                    " Each sampled set runs once with deterministic transitions, so "
                    "`NUM_REPS` is exported as 1 and ignored — the ensemble size is "
                    "`NUM_PARAM_SETS`."
                )
        _scen_note = mo.callout(
            mo.md(
                f"`SCENARIOS` pre-populated from the Analysis tab "
                f"(**{_n_analysis}** scenario(s) + baseline). Run settings "
                f"(`NUM_DAYS`/`NUM_REPS`/`STOCHASTIC`/`TIMESTEPS_PER_DAY`/`SEED_BASE`) "
                f"mirror the Analysis tab, so the script reproduces that run as-is. "
                f"Edit the script to add or change scenarios.{_sp_note_extra}{_unc_note_extra}"
            ),
            kind="info",
        )
    else:
        _scen_note = mo.callout(
            mo.md(
                "No Analysis scenarios defined — only `baseline` is included in `SCENARIOS`. "
                "Define scenarios in the Analysis tab to pre-populate this block."
            ),
            kind="info",
        )

    _metapop_note = (
        "\n\n**Metapopulation:** this is a metapop model, so the script sets "
        "`IS_METAPOP = True` and reads its inputs (per-subpop schedules / initial "
        "conditions, travel matrix) from `METAPOP_FOLDER` at run time. That folder "
        "is **not** bundled into the download — keep it in place, or edit "
        "`METAPOP_FOLDER` to point at it. A fitted m(t) is reconstructed and "
        "broadcast uniformly to every subpopulation."
        if (is_metapop and metapop_folder_input.value.strip()) else ""
    )
    _how_to = mo.callout(
        mo.md(
            "**How to run**\n\n"
            "1. Download `run_simulation.py`, `model_config.json`, and "
            "`fitted_params.json` below into one folder.\n"
            "2. (Optional) edit the `SCENARIOS` block and top constants in the script. "
            "`fitted_params.json` here is the full fit export (`best_params` + "
            "`scale_groups`/`num_days`/`tv_knot_spacing_days`) so the script can also "
            "reproduce fitted `seed_scale_*` (seeded-compartment scaling) and `m_dlog_*` "
            "(time-varying transmission m(t)) — not just plain scalar/array param "
            "overrides. To use a different fit, replace it with any file exported from "
            "the Fitting/Analysis tabs and point `FITTED_PARAMS_FILE` at it — or set it "
            "to `None` to skip overriding.\n"
            "3. Run `python run_simulation.py` — results are written to a "
            "`simulation_output/` folder alongside the script."
            + _metapop_note
        ),
        kind="info",
    )
    mo.vstack([
        mo.Html(
            f'<div style="font-size:1.35rem;font-weight:800;color:{_ACC};">Export</div>'
            '<div style="color:#777;margin:.1rem 0 .2rem;">Generate a standalone '
            "script to run this model outside the notebook.</div>"
        ),
        section_card(
            step_header("①", "Generated script",
                        "A runnable run_simulation.py — edit SCENARIOS and the top "
                        "constants before running.",
                        accent=_ACC),
            mo.vstack([
                _how_to,
                _scen_note,
                # Rendered with code_editor rather than a mo.md ```python fence:
                # markdown routes fenced code through pymdownx/pygments, and
                # pymdownx 10.21 + pygments 2.20 raise AttributeError ('NoneType'
                # has no attribute 'replace') on any fence containing a blank line
                # followed by an indented line — i.e. essentially every real Python
                # script. code_editor highlights client-side and never touches
                # pygments.
                mo.accordion({
                    "run_simulation.py": mo.ui.code_editor(
                        value=_script, language="python", disabled=True,
                    )
                }),
            ]),
            accent=_ACC,
        ),
        section_card(
            step_header("②", "Downloads",
                        "Grab the script and its input files.", accent=_ACC),
            mo.vstack([
                mo.hstack(
                    [_config_dl, _script_dl, _fitted_dl]
                    + ([_schedules_dl] if _schedules_payload else []),
                    justify="start",
                ),
                (
                    mo.md(
                        "*`schedules.json` carries the uploaded "
                        f"{', '.join(f'`{_k}`' for _k in sorted(_schedules_payload))} — "
                        "keep it next to `run_simulation.py` or the run falls back to flat "
                        "constants (no seasonal forcing, no vaccination).*"
                    )
                    if _schedules_payload else mo.md("")
                ),
                mo.md(f"*Outputs auto-saved to `{output_dir}/`*"),
            ]),
            accent=_ACC,
        ),
    ])
    return


# ============================================================
# Analysis tab — sub-tab selector (must depend only on mo)
# ============================================================

