#!/usr/bin/env python3
"""
Generated by CLT Model Builder Notebook (Fitting tab export).
Usage: python run_fitting.py
Reads model_config.json + fit_config.json from this directory and writes
fitted_params.json.

Location: this file must sit exactly two directory levels below the
repo root that contains generic_core/ — e.g. <repo_root>/some_folder/
some_subfolder/run_fitting.py — since it adds
Path(__file__).parent.parent.parent to sys.path to import generic_core.
model_config.json and fit_config.json must sit alongside it in that
same directory.
If you move this file, update the sys.path.insert(...) line below:
count how many directories separate this file from the repo root
(the one containing generic_core/), then use that many + 1 .parent
calls from __file__ (equivalently, .parent calls on _HERE equal to
that count). Also make sure model_config.json / fit_config.json are
still next to this file.
"""

import sys
import json
import io
from pathlib import Path
from types import SimpleNamespace

MODEL_CONFIG_FILE = "model_config.json"
FIT_CONFIG_FILE = "fit_config.json"
OUTPUT_FILE = "fitted_params.json"

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE.parent.parent))

import numpy as np
import pandas as pd
from generic_core.model_factory import build_compartment_init
from generic_core.fitting import FitTarget, FitConfig, run_fit, fit_result_to_dict


def main():
    with open(_HERE / MODEL_CONFIG_FILE) as _f:
        config_dict = json.load(_f)
    with open(_HERE / FIT_CONFIG_FILE) as _f:
        fit_cfg_raw = json.load(_f)

    compartments = fit_cfg_raw["compartments"]
    is_metapop = fit_cfg_raw["is_metapop"]
    targets = [
        FitTarget(
            variables=_t["variables"], mode=_t["mode"], weight=_t["weight"],
            observed=(np.array(_t["observed"], dtype=float) if _t["mode"] == "ts" else _t["observed"]),
            point_weights=(
                np.array(_t["point_weights"], dtype=float)
                if _t.get("point_weights") is not None else None
            ),
            label=_t["label"], subpop_idx=_t["subpop_idx"], age_idx=_t["age_idx"], risk_idx=_t["risk_idx"],
        )
        for _t in fit_cfg_raw["targets"]
    ]
    _fc = fit_cfg_raw["fit_config"]
    fit_config = FitConfig(
        selected_params=_fc["selected_params"],
        bounds={_k: tuple(_v) for _k, _v in _fc["bounds"].items()},
        param_dims=_fc["param_dims"],
        scale_groups=_fc.get("scale_groups", {}),
        log_params=_fc.get("log_params", []),
        method=_fc["method"], lr=_fc["lr"], n_iter=_fc["n_iter"],
        n_replications=_fc["n_replications"], r2_threshold=_fc["r2_threshold"],
        sim_days=_fc["sim_days"], fit_start_offset=_fc["fit_start_offset"],
        start_offset_bounds=tuple(_fc["start_offset_bounds"]),
        robust_steps=_fc.get("robust_steps", True),
        parallel=_fc.get("parallel", True),
        n_workers=_fc.get("n_workers"),
        n_walkers=_fc.get("n_walkers", 32),
        mcmc_burnin=_fc.get("mcmc_burnin", 500),
        mcmc_thin=_fc.get("mcmc_thin", 10),
        abc_pop_size=_fc.get("abc_pop_size", 200),
        abc_max_gens=_fc.get("abc_max_gens", 12),
        tv_transmission=_fc.get("tv_transmission", False),
        tv_knot_spacing_days=_fc.get("tv_knot_spacing_days", 30),
        tv_tau=_fc.get("tv_tau", 0.25),
    )

    _rk = fit_cfg_raw["run_kwargs"]
    num_age_groups = _rk["num_age_groups"]
    num_risk_groups = _rk["num_risk_groups"]

    compartment_init = None
    if not is_metapop:
        _ic_entry = config_dict.get("initial_conditions", {}).get("aggregate_pop", {})
        _pop_arr = np.asarray(
            _ic_entry.get("population", np.zeros((num_age_groups, num_risk_groups))), dtype=float,
        )
        _seed_arrays = {
            _c: np.asarray(_a, dtype=float)
            for _c, _a in (_ic_entry.get("seeds", {}) or {}).items()
            if _c in compartments
        }
        compartment_init, _ = build_compartment_init(_seed_arrays, _pop_arr, compartments)

    # Reconstruct the real uploaded schedule CSVs (so any time-varying vaccination
    # schedule, and its backfill/delay preprocessing, is reproduced exactly). Any
    # field missing from schedule_csvs (no CSV uploaded for it) becomes None, same
    # as the notebook's loaded_schedule_dfs, and model_factory falls back to a
    # constant for that field accordingly.
    schedule_dfs = None
    _sched_csvs = fit_cfg_raw.get("schedule_csvs")
    if _sched_csvs is not None:
        _sched_fields = ("absolute_humidity_df", "school_work_calendar_df", "mobility_df", "daily_vaccines_df")
        schedule_dfs = SimpleNamespace(**{
            _name: (pd.read_csv(io.StringIO(_sched_csvs[_name])) if _name in _sched_csvs else None)
            for _name in _sched_fields
        })

    result = run_fit(
        config_dict=config_dict,
        compartments=compartments,
        is_metapop=is_metapop,
        targets=targets,
        fit_config=fit_config,
        compartment_init=compartment_init,
        schedule_dfs=schedule_dfs,
        start_date=_rk["start_date"],
        ts_per_day=_rk["ts_per_day"],
        seed_base=_rk["seed_base"],
        num_age_groups=num_age_groups,
        num_risk_groups=num_risk_groups,
        metapop_folder=_rk["metapop_folder"],
        metapop_travel_config=_rk["metapop_travel_config"],
        subpop_names=tuple(_rk["subpop_names"]),
        mobility_value=_rk["mobility_value"],
        daily_vaccines_value=_rk["daily_vaccines_value"],
    )

    Path(OUTPUT_FILE).write_text(json.dumps(fit_result_to_dict(result), indent=2))
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    # Gradient methods (Adam/L-BFGS) run replications across a process pool
    # by default (FitConfig.parallel=True) — this guard is required on
    # macOS/Windows, which spawn fresh interpreters for worker processes that
    # re-import this file.
    main()
