#!/usr/bin/env python3
"""
Generated by CLT Model Builder Notebook.
Usage: python generic_core/examples/MA_vax/run_simulations_MA_vax.py

Location: this file must sit exactly two directory levels below the
repo root that contains generic_core/, clt_toolkit/ and flu_core/ —
e.g. <repo_root>/some_folder/some_subfolder/run_simulation.py — since
it adds Path(__file__).parent.parent.parent to sys.path to import
them. model_config.json (and fitted_params.json, if used) must sit
alongside it in that same directory.
If you move this file, update the sys.path.insert(...) line below:
count how many directories separate this file from the repo root,
then use that many + 1 .parent calls from __file__ (equivalently,
.parent calls on _HERE equal to that count). Also make sure
model_config.json / fitted_params.json are still next to this file.
"""

import sys
import io
import os
import json
import copy
import itertools
import numpy as np
import pandas as pd
import sqlite3
from pathlib import Path
from types import SimpleNamespace
from concurrent.futures import ProcessPoolExecutor, as_completed

# ---- Configurable ----
MODEL_CONFIG_FILE = "model_config.json"
FITTED_PARAMS_FILE = "fitted_params.json"  # set to None to skip
# Real uploaded schedule CSVs (humidity / school-work calendar / mobility /
# vaccination), single-population only. Without this file the script falls
# back to flat constants (no seasonal forcing, NO vaccination), which is a
# materially different model than the one built in the notebook. Set to None
# only if the model genuinely has no such inputs.
SCHEDULES_FILE = "schedules.json"
# Transition variables (daily flows, e.g. I_to_H / IV_to_H) to record
# alongside the compartments. None = every transition in model_config.json;
# set to a list to record only some, or [] for compartments only.
TRANSITION_VARS = None
OUTPUT_DIR = Path("simulation_output")
NUM_DAYS = 250
NUM_REPS = 1
STOCHASTIC = False
TIMESTEPS_PER_DAY = 7
START_DATE = "2025-09-01"
NUM_AGE_GROUPS = 7
NUM_RISK_GROUPS = 1
# Base RNG seed; each run uses default_rng(SEED_BASE + run_index), matching
# the notebook's Analysis tab.
SEED_BASE = 42
# Scenario x replicate runs are independent, so they run in a process pool
# (real OS processes -- CPU-bound numpy/Python simulation work would not
# benefit from threads because of the GIL). None = os.cpu_count(); set to 1
# to run serially (e.g. for easier debugging/tracebacks).
NUM_WORKERS = None

# Where the spread between replicates comes from (mirrors the Analysis tab's
# "Uncertainty source" control):
#   "transitions"            - every replicate uses the fitted BEST parameter
#                              set and differs only in the transition RNG.
#   "parameters"             - draw NUM_PARAM_SETS sets at random (without
#                              replacement) from the fit's accepted_params and
#                              run each ONE time with DETERMINISTIC transitions.
#                              The spread is parameter uncertainty alone, with
#                              no transition RNG noise, so repeating a set
#                              would only duplicate its trajectory -- NUM_REPS
#                              is ignored and the ensemble size is the number
#                              of sampled sets.
#   "parameters+transitions" - draw NUM_PARAM_SETS sets at random (without
#                              replacement) from the fit's accepted_params and
#                              spread NUM_REPS replicates evenly across them,
#                              so the ensemble carries parameter uncertainty
#                              too.
# Both sampling modes require a fitted_params.json with more than one accepted
# set, and both are ignored when STOCHASTIC is False (deterministic always runs
# once, with the best set).
UNCERTAINTY_SOURCE = "transitions"
NUM_PARAM_SETS = 10
# Whether the transition engine itself is stochastic. Derived, not a setting:
# the "parameters" mode is stochastic in the sense that it samples the
# posterior, but each run's transitions are deterministic.
RUN_STOCHASTIC = STOCHASTIC and UNCERTAINTY_SOURCE != "parameters"

# Metapopulation reproduction (set by the notebook). When IS_METAPOP is
# True the script builds the model from METAPOP_FOLDER's inputs; that
# folder must exist at run time (edit the path below if you move it).
IS_METAPOP = False
METAPOP_FOLDER = ''
METAPOP_TRAVEL_CONFIG = {}

# Define scenarios: {name: {param: value}}
#
# Scalar params take a number. Array params (per age/risk group) take the
# FULL nested list, shape [num_age_groups][num_risk_groups] -- the values
# below are written out in full, so unlike the notebook's Analysis tab
# (which only offers one uniform 'xscale' factor per scenario) you can set
# each element independently by editing the literal:
#
#     "uniform_x2":  {"I_to_H_prop": [[0.02], [0.02], [0.02]]},
#     "worse_in_65+": {"I_to_H_prop": [[0.01], [0.02], [0.20]]},
#
# Any param you set here must also be listed in DESIGNED_PARAMS below to
# survive parameter sampling -- see the note there.
SCENARIOS = {
    "baseline": {},
    'children vax only': {"beta_baseline": 0.03785553733734781, "relative_suscept": 1.0, "humidity_impact": 0.8756059309429687, "E_to_I_rate": 0.5, "I_out_rate": 0.333, "EV_to_IV_rate": 0.5, "H_out_rate": 0.17, "I_relative_infectiousness": 1.0, "IV_relative_infectiousness": 1.0, "I_to_H_prop": [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], "vax_susceptibility": [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], "IV_to_H_prop": [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], "H_to_D_prop": [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    'Infection protection only': {"beta_baseline": 0.03785553733734781, "relative_suscept": 1.0, "humidity_impact": 0.8756059309429687, "E_to_I_rate": 0.5, "I_out_rate": 0.333, "EV_to_IV_rate": 0.5, "H_out_rate": 0.17, "I_relative_infectiousness": 1.0, "IV_relative_infectiousness": 1.0, "I_to_H_prop": [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], "vax_susceptibility": [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], "IV_to_H_prop": [[0.011609229848373464], [0.012291835171300428], [0.0033475862004129953], [0.002667012915133566], [0.0026131376820989383], [0.006872625697349286], [0.08525342777885123]], "H_to_D_prop": [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    'no vax': {"beta_baseline": 0.03785553733734781, "relative_suscept": 1.0, "humidity_impact": 0.8756059309429687, "E_to_I_rate": 0.5, "I_out_rate": 0.333, "EV_to_IV_rate": 0.5, "H_out_rate": 0.17, "I_relative_infectiousness": 1.0, "IV_relative_infectiousness": 1.0, "I_to_H_prop": [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], "vax_susceptibility": [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], "IV_to_H_prop": [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], "H_to_D_prop": [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    # Below: ported from MA_vax/counterfactual.py's scenario builders (single_age_only_scenario,
    # VE_SCENARIOS, coverage_70pct_scenario) -- see counterfactual_generic.py in this folder for
    # the reusable/table-computing version these values were generated from. "Low VE"/"High VE"
    # use the same vax_susceptibility/IV_to_H_prop multipliers as MA_vax.counterfactual.VE_SCENARIOS.
    # "70% coverage (...)" dose multipliers are a NAIVE cross-product estimate (target coverage /
    # baseline coverage from one deterministic run), not a bisection-refined one -- see
    # counterfactual_generic.py's module docstring.
    "Vaccinate 0 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 1-4 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 5-12 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 13-17 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 18-49 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 50-64 only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Vaccinate 65+ only": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "Low VE": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.669978], [0.669978], [0.669978], [0.669978], [0.940021], [0.940021], [1.0]], 'IV_to_H_prop': [[0.01160614643766853], [0.012288570460665399], [0.003346697081732354], [0.00266630455667395], [0.002507928838932415], [0.006595923476839474], [0.06734858814498136]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "High VE": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.48997199999999996], [0.48997199999999996], [0.48997199999999996], [0.48997199999999996], [0.659966], [0.659966], [0.86]], 'IV_to_H_prop': [[0.005211225393742428], [0.0055176376397915615], [0.0015026859182892397], [0.001197185826304432], [0.002207263046471889], [0.005805163975059858], [0.06047196140539859]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    # Below: added by hand (not exported by the notebook's Analysis tab) --
    # same param overrides as "Low VE"/"High VE" above, combined with the
    # "70% coverage (all ages)" dose schedule below, so Table S.A.6 (which
    # compares each VE scenario's OWN baseline to its OWN 70%-coverage
    # target) can be built purely from this script's SCENARIOS, matching
    # counterfactual_generic.py's table_S_A_6.
    "Low VE + 70% coverage (all ages)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.669978], [0.669978], [0.669978], [0.669978], [0.940021], [0.940021], [1.0]], 'IV_to_H_prop': [[0.01160614643766853], [0.012288570460665399], [0.003346697081732354], [0.00266630455667395], [0.002507928838932415], [0.006595923476839474], [0.06734858814498136]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "High VE + 70% coverage (all ages)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.48997199999999996], [0.48997199999999996], [0.48997199999999996], [0.48997199999999996], [0.659966], [0.659966], [0.86]], 'IV_to_H_prop': [[0.005211225393742428], [0.0055176376397915615], [0.0015026859182892397], [0.001197185826304432], [0.002207263046471889], [0.005805163975059858], [0.06047196140539859]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (all ages)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (0 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (1-4 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (5-12 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (13-17 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (18-49 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (50-64 only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
    "70% coverage (65+ only)": {'beta_baseline': 0.03785553733734781, 'relative_suscept': 1.0, 'humidity_impact': 0.8756059309429687, 'E_to_I_rate': 0.5, 'I_out_rate': 0.333, 'EV_to_IV_rate': 0.5, 'H_out_rate': 0.17, 'I_relative_infectiousness': 1.0, 'IV_relative_infectiousness': 1.0, 'I_to_H_prop': [[0.011609229849277137], [0.012291835172257237], [0.0033475861997276433], [0.0026670129145875483], [0.0026131376817063985], [0.00687262569769161], [0.08525342779407329]], 'vax_susceptibility': [[0.57], [0.57], [0.57], [0.57], [0.79], [0.79], [1.0]], 'IV_to_H_prop': [[0.010587617622394206], [0.01121015367694344], [0.0030529986149720433], [0.0024323157787574804], [0.002380568428032667], [0.006260962009339795], [0.058824865180348816]], 'H_to_D_prop': [[0.01741109215], [0.01741109215], [0.0117181651], [0.0117181651], [0.02633277317], [0.06301864177], [0.07988898095]]},
}

# Per-subpopulation parameter overrides per scenario (metapop only)
# Format: {scenario_name: [override_dict_or_None, ...]} indexed by subpop order
SUBPOP_PARAM_OVERRIDES = {
}

# Parameters each scenario deliberately sets: {scenario_name: [param, ...]}.
#
# Only relevant when UNCERTAINTY_SOURCE samples parameters. Each run
# takes its parameters from a sampled fitted set, EXCEPT the ones listed here
# for that scenario, which keep the value given in SCENARIOS. Without this,
# the sampled set would overwrite the very parameter the scenario varies and
# every scenario would collapse to the same thing.
#
# A parameter that is in SCENARIOS but NOT in this list for that scenario is
# deliberately NOT protected: it comes from the sampled parameter set, and the
# SCENARIOS value is ignored. That is what makes the non-varied parameters
# carry posterior uncertainty. The notebook lists exactly the parameters you
# changed away from the fitted baseline, so its scenarios behave as designed.
#
# If you ADD a scenario by hand, add it here too. A scenario name missing from
# this dict falls back to protecting everything it sets in SCENARIOS (safe for
# hand-written scenarios, but it means none of its params carry parameter
# uncertainty). Use an explicit empty list to opt a scenario fully into
# sampling.
DESIGNED_PARAMS = {
    'children vax only': [],
    'Infection protection only': ['IV_to_H_prop'],
    'no vax': [],
    'Vaccinate 0 only': [], 'Vaccinate 1-4 only': [], 'Vaccinate 5-12 only': [],
    'Vaccinate 13-17 only': [], 'Vaccinate 18-49 only': [], 'Vaccinate 50-64 only': [],
    'Vaccinate 65+ only': [],
    'Low VE': ['vax_susceptibility', 'IV_to_H_prop'],
    'High VE': ['vax_susceptibility', 'IV_to_H_prop'],
    'Low VE + 70% coverage (all ages)': ['vax_susceptibility', 'IV_to_H_prop'],
    'High VE + 70% coverage (all ages)': ['vax_susceptibility', 'IV_to_H_prop'],
    '70% coverage (all ages)': [], '70% coverage (0 only)': [], '70% coverage (1-4 only)': [],
    '70% coverage (5-12 only)': [], '70% coverage (13-17 only)': [], '70% coverage (18-49 only)': [],
    '70% coverage (50-64 only)': [], '70% coverage (65+ only)': [],
}

# Ratio (override / catalog baseline) for designed params, where known:
# {scenario_name: {param: ratio_or_nested_list}}.
#
# Only relevant when UNCERTAINTY_SOURCE samples parameters. A designed
# param listed here has the sampled draw's own value scaled by this ratio
# instead of being pinned to the literal value in SCENARIOS -- so the
# scenario's intended scaling survives parameter uncertainty. A designed
# param NOT listed here (or added by hand) falls back to being pinned to
# the literal SCENARIOS value on every draw.
DESIGNED_PARAM_RATIOS = {
    'Infection protection only': {'IV_to_H_prop': [[1.096491228], [1.096491228], [1.096491228], [1.096491228], [1.097694841], [1.097694841], [1.449275362]]},
    'Low VE': {
        'vax_susceptibility': [[1.1754], [1.1754], [1.1754], [1.1754], [1.1899], [1.1899], [1.0]],
        'IV_to_H_prop': [[1.0962], [1.0962], [1.0962], [1.0962], [1.0535], [1.0535], [1.1449]],
    },
    'High VE': {
        'vax_susceptibility': [[0.8596], [0.8596], [0.8596], [0.8596], [0.8354], [0.8354], [0.86]],
        'IV_to_H_prop': [[0.4922], [0.4922], [0.4922], [0.4922], [0.9272], [0.9272], [1.028]],
    },
    'Low VE + 70% coverage (all ages)': {
        'vax_susceptibility': [[1.1754], [1.1754], [1.1754], [1.1754], [1.1899], [1.1899], [1.0]],
        'IV_to_H_prop': [[1.0962], [1.0962], [1.0962], [1.0962], [1.0535], [1.0535], [1.1449]],
    },
    'High VE + 70% coverage (all ages)': {
        'vax_susceptibility': [[0.8596], [0.8596], [0.8596], [0.8596], [0.8354], [0.8354], [0.86]],
        'IV_to_H_prop': [[0.4922], [0.4922], [0.4922], [0.4922], [0.9272], [0.9272], [1.028]],
    },
}

# Per-age-group multiplier on a `scheduled_exact` transition's daily
# schedule, per scenario (a schedule override, not a params entry).
# Despite the "vaccine" naming baked into the model config schema
# (daily_vaccines_df), scheduled_exact isn't vaccine-specific -- this
# scales whatever it represents (antiviral courses, etc.). Applies to
# every subpop identically in a metapop run, except where overridden by
# DOSE_MULTIPLIER_PER_SUBPOP below.
# Format: {scenario_name: [multiplier_per_age_group, ...]}
DOSE_MULTIPLIER = {
    'children vax only': [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
    'no vax': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'Vaccinate 0 only': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'Vaccinate 1-4 only': [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'Vaccinate 5-12 only': [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
    'Vaccinate 13-17 only': [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
    'Vaccinate 18-49 only': [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
    'Vaccinate 50-64 only': [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
    'Vaccinate 65+ only': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    # Naive cross-product coverage multiplier (target 0.70 / baseline coverage from one
    # deterministic run) -- see the SCENARIOS comment above and counterfactual_generic.py.
    '70% coverage (all ages)': [1.5618042287606673, 0.7812223996432112, 1.0077209653521768, 1.2943827994844874, 1.8061652849458125, 1.2047962088514907, 0.9840824933555715],
    # Unlike the 'Vaccinate X only' scenarios above, the untargeted age groups keep
    # their baseline schedule (multiplier 1.0, not 0.0): Table S.A.3 compares these
    # against 'baseline', so it measures the ADDITIONAL benefit of raising one age
    # group to 70%, not the net effect of also de-vaccinating everyone else. Matches
    # counterfactual_generic.py's coverage_70pct_scenario (np.ones base).
    '70% coverage (0 only)': [1.5618042287606673, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
    '70% coverage (1-4 only)': [1.0, 0.7812223996432112, 1.0, 1.0, 1.0, 1.0, 1.0],
    '70% coverage (5-12 only)': [1.0, 1.0, 1.0077209653521768, 1.0, 1.0, 1.0, 1.0],
    '70% coverage (13-17 only)': [1.0, 1.0, 1.0, 1.2943827994844874, 1.0, 1.0, 1.0],
    '70% coverage (18-49 only)': [1.0, 1.0, 1.0, 1.0, 1.8061652849458125, 1.0, 1.0],
    '70% coverage (50-64 only)': [1.0, 1.0, 1.0, 1.0, 1.0, 1.2047962088514907, 1.0],
    '70% coverage (65+ only)': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9840824933555715],
    # Same dose multiplier as '70% coverage (all ages)' -- coverage (S_to_SV)
    # is driven by the dose schedule, not by vax_susceptibility/IV_to_H_prop,
    # so the Low/High VE scenarios reach the same coverage target.
    'Low VE + 70% coverage (all ages)': [1.5618042287606673, 0.7812223996432112, 1.0077209653521768, 1.2943827994844874, 1.8061652849458125, 1.2047962088514907, 0.9840824933555715],
    'High VE + 70% coverage (all ages)': [1.5618042287606673, 0.7812223996432112, 1.0077209653521768, 1.2943827994844874, 1.8061652849458125, 1.2047962088514907, 0.9840824933555715],
}

# Per-subpopulation override of DOSE_MULTIPLIER above (metapop only).
# Format: {scenario_name: [multiplier_per_age_group_or_None, ...]}
# indexed by subpop order; a None entry falls back to DOSE_MULTIPLIER.
DOSE_MULTIPLIER_PER_SUBPOP = {
}

# ---- Setup ----
_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE.parent.parent))

import clt_toolkit as clt
import flu_core as flu
from generic_core.config_parser import parse_model_config_from_dict
from generic_core.generic_model import (
    ConfigDrivenSubpopModel, build_state_from_config, build_params_from_config,
)
from generic_core.generic_metapop import ConfigDrivenMetapopModel
from generic_core.model_factory import (
    build_compartment_init, make_metapop_from_folder, extract_history,
    extract_history_full, scale_dose_schedule_df,
)
from generic_core.fitting import (
    _scale_compartment_init, _inject_tv_transmission, _tv_knot_days,
    build_transmission_multiplier_array, prepare_param_sets,
)

with open(_HERE / MODEL_CONFIG_FILE) as _f:
    config_dict = json.load(_f)

if TRANSITION_VARS is None:
    TRANSITION_VARS = [
        _t["name"] for _t in config_dict.get("transitions", []) if _t.get("name")
    ]
else:
    TRANSITION_VARS = list(TRANSITION_VARS)

# Fitted params can carry three kinds of entries:
#  - regular config["params"] scalars/arrays  -> merged in directly below
#  - seed_scale_<comp>  -> scales that seeded compartment's initial condition
#    (mirrors generic_core.fitting._scale_compartment_init); applied in
#    build_model(), not a config["params"] entry
#  - m_dlog_*  -> log-increments of the fitted time-varying transmission
#    multiplier m(t); reconstructed in build_model() via a
#    'transmission_multiplier' schedule (mirrors
#    generic_core.fitting._inject_tv_transmission), exact over the fit period
#    (FIT_NUM_DAYS) and held flat at its last value beyond it.
#  - phi (NB2 observation-noise dispersion) and linked-scale multiplier keys
#    (see SCALE_GROUPS) are not model parameters and are dropped/expanded.
SEED_SCALES = {}
TV_INCREMENTS = []
TV_SPACING = 30
FIT_NUM_DAYS = 0
# Accepted/posterior parameter sets behind the best set, used only when
# UNCERTAINTY_SOURCE samples parameters ("parameters" / "parameters+transitions").
PARAM_SETS = []


def _split_pset(_pset):
    # A prepared param set mixes three kinds of entry. Split them the way
    # each is actually applied: model params merge into config["params"],
    # seed_scale_* scales the initial conditions, m_dlog_* rebuilds m(t).
    # phi (NB2 observation-noise dispersion) is not a model parameter.
    _model = {
        _k: _v for _k, _v in _pset.items()
        if _k != "phi" and not _k.startswith("m_dlog_") and not _k.startswith("seed_scale_")
    }
    _scales = {
        _k[len("seed_scale_"):]: float(_v)
        for _k, _v in _pset.items() if _k.startswith("seed_scale_")
    }
    _incr = [
        _v for _, _v in sorted(
            (
                (int(_k[len("m_dlog_"):]), float(_v))
                for _k, _v in _pset.items()
                if _k.startswith("m_dlog_") and _k[len("m_dlog_"):].isdigit()
            ),
            key=lambda _t: _t[0],
        )
    ]
    return _model, _scales, _incr


if FITTED_PARAMS_FILE is not None:
    _fp = _HERE / FITTED_PARAMS_FILE
    if _fp.exists():
        with open(_fp) as _f:
            _fitted_raw = json.load(_f)
    else:
        print(f"Warning: {FITTED_PARAMS_FILE} not found")
        _fitted_raw = {}

    _best_params = _fitted_raw.get("best_params", _fitted_raw) if isinstance(_fitted_raw, dict) else {}
    _accepted = (_fitted_raw.get("accepted_params") or []) if isinstance(_fitted_raw, dict) else []
    _scale_groups = (_fitted_raw.get("scale_groups", {}) or {}) if isinstance(_fitted_raw, dict) else {}
    FIT_NUM_DAYS = int(_fitted_raw.get("num_days", 0) or 0) if isinstance(_fitted_raw, dict) else 0
    TV_SPACING = int(_fitted_raw.get("tv_knot_spacing_days", 30) or 30) if isinstance(_fitted_raw, dict) else 30

    # prepare_param_sets reassembles MCMC/ABC-SMC per-element sampler columns
    # (`pn|a0`, `pn|a1`, ... — AR/gradient record one array-valued `pn`
    # directly) and expands linked-scale multipliers into concrete
    # base-param values (base := model_config baseline × multiplier). Both
    # must be resolved against the ORIGINAL (pre-fit) config baseline, so
    # capture it before config_dict["params"] is updated below.
    _orig_params = dict(config_dict.get("params", {}) or {})
    _expanded = prepare_param_sets([_best_params], _scale_groups, _orig_params)[0]
    PARAM_SETS = prepare_param_sets(_accepted, _scale_groups, _orig_params)

    FITTED_PARAMS, SEED_SCALES, TV_INCREMENTS = _split_pset(_expanded)
    if TV_INCREMENTS and FIT_NUM_DAYS <= 0:
        print("Warning: fitted params have m_dlog_* but no num_days — m(t) will not be reconstructed")
        TV_INCREMENTS = []
    config_dict["params"] = {**config_dict.get("params", {}), **FITTED_PARAMS}

    if SEED_SCALES:
        print(f"Applying fitted seed scaling to: {sorted(SEED_SCALES)}")
    if TV_INCREMENTS:
        print(
            f"Reconstructing m(t) from {len(TV_INCREMENTS)} fitted log-increment(s) "
            f"(fit period {FIT_NUM_DAYS} days, knots every {TV_SPACING} days)"
        )

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _build_tvm_df(start_date, num_days, tv_increments=None):
    # Reconstruct the fitted m(t) trajectory: exact over the fit period
    # (FIT_NUM_DAYS) and held flat at its last value beyond it. Returns None
    # when no m(t) was fit. Shared by the single-pop schedules and the metapop
    # build (where it is broadcast identically to every subpop).
    # tv_increments defaults to the best set's; a sampled param set passes
    # its own (each posterior draw carries its own m(t) trajectory).
    _incr = TV_INCREMENTS if tv_increments is None else tv_increments
    if not _incr or FIT_NUM_DAYS <= 0:
        return None
    _h = max(num_days + 14, 370)
    _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
    _knots = _tv_knot_days(FIT_NUM_DAYS, TV_SPACING)
    _m_fit = build_transmission_multiplier_array(_incr, _knots, FIT_NUM_DAYS)
    if _h <= FIT_NUM_DAYS:
        _m_full = _m_fit[:_h]
    else:
        _m_full = np.concatenate([_m_fit, np.full(_h - FIT_NUM_DAYS, _m_fit[-1])])
    return pd.DataFrame({"date": _dates, "transmission_multiplier": _m_full})


def _load_schedule_csvs():
    # The uploaded schedule CSVs, saved alongside this script by the Export
    # tab. Any attribute absent here had no CSV uploaded in the notebook and
    # correctly falls back to a flat constant below.
    if not SCHEDULES_FILE:
        return {}
    _p = _HERE / SCHEDULES_FILE
    if not _p.exists():
        print(
            f"Warning: {SCHEDULES_FILE} not found next to this script — falling back to "
            "flat constant schedules (no seasonal forcing, no vaccination). Results will "
            "NOT match the notebook. Re-download schedules.json from the Export tab."
        )
        return {}
    with open(_p) as _f:
        return json.load(_f)


def _build_schedules(start_date, num_days, tv_increments=None, dose_mult=None):
    # dose_mult: per-age-group multiplier on the `scheduled_exact`
    # transition's daily schedule (see scale_dose_schedule_df) -- e.g. 0 to
    # zero out an age group for a no-dose / single-age-only scenario.
    # Despite the "daily_vaccines" naming (fixed by the model config
    # schema), this isn't vaccine-specific -- it scales whatever
    # `scheduled_exact` represents (antiviral prophylaxis courses, etc.).
    _h = max(num_days + 14, 370)
    _dates = pd.date_range(start=start_date, periods=_h, freq="D").date
    _mob = json.dumps(np.ones((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    _vax = json.dumps(np.zeros((NUM_AGE_GROUPS, NUM_RISK_GROUPS)).tolist())
    _csvs = _load_schedule_csvs()

    def _real_or(_name, _fallback):
        if _name in _csvs:
            return pd.read_csv(io.StringIO(_csvs[_name]))
        return _fallback

    _kwargs = {}
    _tvm_df = _build_tvm_df(start_date, num_days, tv_increments)
    if _tvm_df is not None:
        _kwargs["transmission_multiplier_df"] = _tvm_df
    return SimpleNamespace(
        absolute_humidity_df=_real_or(
            "absolute_humidity_df",
            pd.DataFrame({"date": _dates, "absolute_humidity": [0.01] * _h})),
        school_work_calendar_df=_real_or(
            "school_work_calendar_df",
            pd.DataFrame({"date": _dates, "is_school_day": [1.0] * _h, "is_work_day": [1.0] * _h})),
        mobility_df=_real_or(
            "mobility_df",
            pd.DataFrame({"day_of_week": ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"], "mobility_modifier": [_mob]*7})),
        daily_vaccines_df=scale_dose_schedule_df(_real_or(
            "daily_vaccines_df",
            pd.DataFrame({"date": _dates, "daily_vaccines": [_vax] * _h})), dose_mult),
        **_kwargs,
    )


def build_model(cfg, param_overrides, rep, subpop_overrides=None,
                seed_scales=None, tv_increments=None,
                dose_mult=None, dose_mult_per_subpop=None):
    # subpop_overrides: list of {param: value} indexed by subpop order (metapop only)
    # seed_scales / tv_increments default to the fitted best set's; a sampled
    # param set passes its own so each run reproduces that draw's initial
    # conditions and m(t) trajectory.
    # dose_mult / dose_mult_per_subpop: per-age-group multiplier(s) on a
    # `scheduled_exact` transition's daily schedule (see
    # scale_dose_schedule_df), mirroring the Analysis tab's schedule-scaling
    # control. dose_mult applies to every subpop identically (or is the only
    # one used, single-population); dose_mult_per_subpop (metapop only) is a
    # list indexed by subpop order whose non-None entries override dose_mult
    # for that subpop.
    _seed_scales = SEED_SCALES if seed_scales is None else seed_scales
    _tv_incr = TV_INCREMENTS if tv_increments is None else tv_increments
    _cfg = copy.deepcopy(cfg)
    if param_overrides:
        _cfg["params"] = {**_cfg.get("params", {}), **param_overrides}
    if _tv_incr:
        _cfg, _ = _inject_tv_transmission(_cfg)

    if IS_METAPOP:
        # Metapop: reuse the folder-driven factory, which reads
        # metapop_config.json, per-subpop schedule CSVs, travel matrix and
        # per-subpop initial conditions. The scenario's shared overrides are
        # already merged into _cfg["params"] above (applied to every subpop);
        # subpop_overrides supplies per-subpop values. The fitted m(t) is
        # reconstructed once and broadcast identically to all subpops.
        _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
        if _seed_scales:
            print(
                "Warning: seed-scale reproduction is not applied for metapop export "
                "(per-subpop seeded initial conditions are read from the metapop folder); "
                f"ignoring fitted seed scales {sorted(_seed_scales)}."
            )
        _m, _ = make_metapop_from_folder(
            METAPOP_FOLDER, _cfg, START_DATE, NUM_DAYS, _comps,
            seed_offset=rep, seed_base=SEED_BASE, ts_per_day=TIMESTEPS_PER_DAY,
            stochastic=RUN_STOCHASTIC, save_daily=True, tvs=TRANSITION_VARS,
            param_overrides=None,
            param_overrides_per_subpop=subpop_overrides,
            travel_config=METAPOP_TRAVEL_CONFIG or None,
            num_age_groups=NUM_AGE_GROUPS, num_risk_groups=NUM_RISK_GROUPS,
            transmission_multiplier_df=_build_tvm_df(START_DATE, NUM_DAYS, _tv_incr),
            dose_mult=dose_mult, dose_mult_per_subpop=dose_mult_per_subpop,
        )
        return _m

    _sched = _build_schedules(START_DATE, NUM_DAYS, _tv_incr, dose_mult)
    _mc = parse_model_config_from_dict(_cfg, schedules_input=_sched)
    _A, _R = NUM_AGE_GROUPS, NUM_RISK_GROUPS
    _comps = list(_cfg.get("compartments", {}).keys()) if isinstance(_cfg.get("compartments"), dict) else list(_cfg.get("compartments", ["S"]))
    _first = _comps[0] if _comps else "S"
    _N = _cfg.get("total_population", 100000)
    # Seeded compartments (e.g. an initial E count) from the Builder's Step 6
    # initial-conditions table, same source Analysis/Forecast read — not just
    # everyone starting in the first compartment.
    _ic_entry = (_cfg.get("initial_conditions", {}) or {}).get("aggregate_pop", {})
    if _ic_entry:
        _pop_arr = np.asarray(_ic_entry.get("population", np.full((_A, _R), float(_N))), dtype=float)
        _seed_arrays = {
            _c: np.asarray(_a, dtype=float)
            for _c, _a in (_ic_entry.get("seeds", {}) or {}).items()
            if _c in _comps
        }
        _comp_init, _ = build_compartment_init(_seed_arrays, _pop_arr, _comps)
    else:
        _comp_init = {_first: np.full((_A, _R), float(_N))}
        for _c in _comps[1:]:
            _comp_init.setdefault(_c, np.zeros((_A, _R)))
    if _seed_scales:
        _comp_init = _scale_compartment_init(_comp_init, _seed_scales, _comps, _A, _R)
    _state = build_state_from_config(_mc, _comp_init, epi_metric_init={})
    _params = build_params_from_config(_mc, num_age_groups=_A, num_risk_groups=_R)
    _tt = clt.TransitionTypes.BINOM if RUN_STOCHASTIC else clt.TransitionTypes.BINOM_DETERMINISTIC_NO_ROUND
    _settings = clt.SimulationSettings(
        timesteps_per_day=TIMESTEPS_PER_DAY, transition_type=_tt,
        start_real_date=START_DATE, save_daily_history=True,
        transition_variables_to_save=TRANSITION_VARS,
    )
    _subpop = ConfigDrivenSubpopModel(
        model_config=_mc, state_init=_state, params=_params,
        simulation_settings=_settings, RNG=np.random.default_rng(SEED_BASE + rep),
        schedules_input=_sched, name="pop",
    )
    _mixing = flu.FluMixingParams(travel_proportions=np.array([[1.0]]), num_locations=1)
    return ConfigDrivenMetapopModel(
        subpop_models=[_subpop], mixing_params=_mixing,
        model_config=_mc, travel_config={},
    )


# ---- Uncertainty source: which parameter set each replicate runs with ----
# Mirrors the Analysis tab. "transitions" (and every deterministic run) uses
# the fitted best set — already merged into config_dict["params"] and into
# each scenario's overrides — so replicates differ only in the transition
# RNG. Otherwise draw NUM_PARAM_SETS sets at random without replacement:
# "parameters" runs each drawn set exactly once (transitions are
# deterministic, so a repeated set would only duplicate its trajectory —
# NUM_REPS is ignored), "parameters+transitions" spreads NUM_REPS replicates
# evenly across the drawn sets (remainder distributed at random).
_param_only = UNCERTAINTY_SOURCE == "parameters"
_use_psets = (
    STOCHASTIC
    and UNCERTAINTY_SOURCE in ("parameters", "parameters+transitions")
    and len(PARAM_SETS) > 1
)
if _use_psets:
    _rng_sched = np.random.default_rng(SEED_BASE)
    _k = min(int(NUM_PARAM_SETS), len(PARAM_SETS), *(() if _param_only else (NUM_REPS,)))
    _sel = _rng_sched.choice(len(PARAM_SETS), size=_k, replace=False)
    RUN_PARAM_SETS = [PARAM_SETS[int(_i)] for _i in _sel]
    if _param_only:
        RUN_SCHEDULE = list(range(_k))
    else:
        _base_r, _extra_r = divmod(NUM_REPS, _k)
        RUN_SCHEDULE = [_i for _i in range(_k) for _ in range(_base_r)]
        if _extra_r:
            RUN_SCHEDULE += [int(_i) for _i in _rng_sched.choice(_k, size=_extra_r, replace=False)]
    if __name__ == "__main__":
        # This module-level block runs again on import in every worker
        # process (spawn re-imports the script as __main__; fork re-runs it
        # too under some pool implementations) since RUN_PARAM_SETS/
        # RUN_SCHEDULE must exist there for _apply_pset. Only print once, in
        # the parent.
        print(
            f"Parameter uncertainty: {_k} set(s) sampled from {len(PARAM_SETS)} accepted, "
            f"{len(RUN_SCHEDULE)} run(s) per scenario"
            + (" (deterministic transitions)" if _param_only else "")
        )
else:
    if (
        __name__ == "__main__"
        and UNCERTAINTY_SOURCE in ("parameters", "parameters+transitions")
        and STOCHASTIC
    ):
        _fallback = (
            "a single deterministic run of the best parameter set"
            if _param_only
            else "transition-only uncertainty with the best parameter set"
        )
        print(
            f"Warning: UNCERTAINTY_SOURCE is '{UNCERTAINTY_SOURCE}' but "
            f"{FITTED_PARAMS_FILE} has fewer than 2 accepted_params — falling back "
            f"to {_fallback}."
        )
    RUN_PARAM_SETS = []
    RUN_SCHEDULE = [None] * (NUM_REPS if RUN_STOCHASTIC else 1)


def _apply_pset(overrides, pset_idx, designed, ratios=None):
    # Layer a sampled param set under the scenario's overrides: the set
    # supplies every fitted param the scenario design did not deliberately
    # set (DESIGNED_PARAMS), so the ensemble carries parameter uncertainty
    # without undoing the sweep or the edited scenario values. Returns the
    # (param_overrides, seed_scales, tv_increments) triple for this run.
    # A designed param with a known ratio in DESIGNED_PARAM_RATIOS (the
    # scenario's override / catalog baseline at export time) instead has
    # that ratio applied to the sampled draw's own value, so the
    # scenario's scaling factor carries through posterior uncertainty
    # rather than pinning one absolute value across every draw.
    if pset_idx is None:
        return overrides, None, None
    _model, _scales, _incr = _split_pset(RUN_PARAM_SETS[pset_idx])
    _ov = dict(overrides or {})
    _ratios = ratios or {}
    for _k2, _v2 in _model.items():
        if _k2 in designed:
            _ratio = _ratios.get(_k2)
            if _ratio is None:
                continue
            if isinstance(_ratio, list):
                _ov[_k2] = (np.asarray(_ratio, dtype=float) * np.asarray(_v2, dtype=float)).tolist()
            else:
                _ov[_k2] = float(_ratio) * float(_v2)
            continue
        _ov[_k2] = _v2
    return _ov, _scales, _incr


def _run_one(scenario_name, overrides, designed, dose_mult, dose_mult_per_subpop,
             ratios, sp_overrides, rep, pset_idx):
    # One (scenario, replicate) unit of work -- everything a pool worker
    # needs is passed in as plain, picklable arguments; module globals used
    # inside (config_dict, NUM_DAYS, TRANSITION_VARS, RUN_PARAM_SETS via
    # _apply_pset, ...) are rebuilt identically in every worker process when
    # it re-imports this script, so they don't need to be passed explicitly.
    _run_ov, _run_scales, _run_incr = _apply_pset(overrides, pset_idx, designed, ratios)
    _m = build_model(
        config_dict, _run_ov, rep, subpop_overrides=sp_overrides,
        seed_scales=_run_scales, tv_increments=_run_incr,
        dose_mult=dose_mult, dose_mult_per_subpop=dose_mult_per_subpop,
    )
    _m.simulate_until_day(NUM_DAYS)
    _sps = list(_m.subpop_models.values())
    _comp_names = list(_sps[0].compartments.keys())
    # extract_history sums over age/risk and subpops, and — critically —
    # aggregates transition variables from per-sub-timestep to per-day.
    # Transition history is saved once per sub-timestep, so summing it
    # raw would give a series TIMESTEPS_PER_DAY x too long and each
    # value TIMESTEPS_PER_DAY x too small.
    _h = extract_history(_m, _comp_names, tvs=TRANSITION_VARS)
    # Fully-resolved companion to _h -- same compartments/transitions,
    # but per-subpop (day, age_group, risk_group) arrays instead of
    # (day,) scalars summed over subpop/age/risk. The counterfactual
    # vaccination-impact tables (S.A.2/S.A.3/S.A.5/S.A.6/VAX_CHECK) all
    # need per-age-group hospitalizations/doses/flows -- extract_history's
    # own summed totals stay the fast path for the population aggregate.
    _h_full = extract_history_full(_m, _comp_names, tvs=TRANSITION_VARS)
    _kinds = {_k: ("transition" if _k in TRANSITION_VARS else "compartment") for _k in _h}
    return scenario_name, rep, pset_idx, _h, _h_full, _kinds


# ---- Everything below only runs in the parent process. ----
# Guarding it is required (not just tidy) on spawn-based multiprocessing
# (the default on macOS and Windows): each pool worker re-imports this file
# as __main__, so without this guard every worker would recursively try to
# build its own pool and re-run the whole scenario sweep. Under fork-based
# multiprocessing (Linux's default) it isn't strictly required, but keeping
# it makes the script behave identically on all three platforms.
if __name__ == "__main__":
    _tasks = []
    for scenario_name, overrides in SCENARIOS.items():
        _sp_overrides = SUBPOP_PARAM_OVERRIDES.get(scenario_name)
        # A scenario absent from DESIGNED_PARAMS was added by hand, so nothing
        # says which of its params are deliberate — protect all of them rather
        # than silently letting a sampled set overwrite the values the user
        # just wrote. An explicit (possibly empty) list always wins.
        if scenario_name in DESIGNED_PARAMS:
            _designed = set(DESIGNED_PARAMS[scenario_name])
        else:
            _designed = set(overrides or {})
        _dose_mult = DOSE_MULTIPLIER.get(scenario_name)
        _dose_mult_per_subpop = DOSE_MULTIPLIER_PER_SUBPOP.get(scenario_name)
        _ratios = DESIGNED_PARAM_RATIOS.get(scenario_name, {})
        # Seed by position in the run schedule so every run gets a distinct
        # RNG stream once replicates are spread across parameter sets.
        for _rep, _pset_idx in enumerate(RUN_SCHEDULE):
            _tasks.append((
                scenario_name, overrides, _designed, _dose_mult,
                _dose_mult_per_subpop, _ratios, _sp_overrides, _rep, _pset_idx,
            ))

    _n_workers = NUM_WORKERS or os.cpu_count() or 1
    _n_workers = min(_n_workers, len(_tasks)) or 1
    print(f"Running {len(_tasks)} simulation(s) across {_n_workers} worker process(es)")

    all_results = {_scen: [] for _scen in SCENARIOS}
    if _n_workers == 1:
        # Serial fallback (NUM_WORKERS = 1) -- also handy for debugging,
        # since a worker-process traceback is otherwise harder to inspect.
        for _t in _tasks:
            _scen, _rep, _psi, _h, _h_full, _kinds = _run_one(*_t)
            all_results[_scen].append((_rep, _h, _h_full, _kinds, _psi))
    else:
        with ProcessPoolExecutor(max_workers=_n_workers) as _ex:
            _futures = {_ex.submit(_run_one, *_t): _t for _t in _tasks}
            for _fut in as_completed(_futures):
                _scen_name = _futures[_fut][0]
                _scen, _rep, _psi, _h, _h_full, _kinds = _fut.result()
                print(f"Finished scenario={_scen_name} rep={_rep}")
                all_results[_scen].append((_rep, _h, _h_full, _kinds, _psi))

    # Pool completion order is nondeterministic; sort each scenario's
    # replicates back into run-schedule order so the `rep` column written to
    # results.db below matches what a serial run would have produced.
    for _scen in all_results:
        all_results[_scen] = [
            (_h, _h_full, _kinds, _psi)
            for (_rep, _h, _h_full, _kinds, _psi) in sorted(all_results[_scen], key=lambda _r: _r[0])
        ]

    _db = OUTPUT_DIR / "results.db"
    _con = sqlite3.connect(_db)
    # results.db is dropped and rebuilt from scratch every run (see below), so
    # it never needs to survive a crash -- skip SQLite's per-write fsync/
    # journaling durability guarantees so writing hundreds of thousands of
    # rows (stochastic runs with many replicates x days x age/risk groups)
    # isn't dominated by disk sync time.
    _con.execute("PRAGMA synchronous = OFF")
    _con.execute("PRAGMA journal_mode = MEMORY")
    _cur = _con.cursor()
    # Drop and recreate both tables every run rather than INSERTing into
    # whatever's already there -- this script has no notion of "replace this
    # scenario's rows", so reusing an existing results.db (e.g. after editing
    # SCENARIOS and rerunning) would otherwise silently accumulate duplicate
    # rows under the same (scenario, rep) key on top of the old ones, corrupting
    # every downstream sum. `results.db` is meant to hold exactly one run's
    # output, not an append-only log across runs.
    _cur.execute("DROP TABLE IF EXISTS results")
    _cur.execute("DROP TABLE IF EXISTS results_full")
    # `compartment` keeps its name (so existing queries still work) but now holds
    # transition-variable names too; `kind` distinguishes them. `param_set` is the
    # index into the sampled parameter sets (NULL when parameter uncertainty is
    # off), so replicates can be grouped by draw.
    _cur.execute(
        "CREATE TABLE results "
        "(scenario TEXT, rep INTEGER, param_set INTEGER, compartment TEXT, kind TEXT, "
        "day INTEGER, value REAL)"
    )
    # Same shape as `results`, plus `subpop`/`age_group`/`risk_group` columns
    # (age_group/risk_group are 0-based indices into NUM_AGE_GROUPS/
    # NUM_RISK_GROUPS, i.e. MA_vax.model.AGE_GROUP_LABELS order for age_group) --
    # kept as a separate table rather than nullable columns on `results`, so
    # `results` alone still answers population-aggregate queries without a
    # GROUP BY. This script's single-population, single-risk-group model gets
    # one subpop name and risk_group=0 throughout -- still queryable the same
    # way, just with nothing to GROUP BY away.
    _cur.execute(
        "CREATE TABLE results_full "
        "(scenario TEXT, rep INTEGER, param_set INTEGER, compartment TEXT, kind TEXT, "
        "subpop TEXT, age_group INTEGER, risk_group INTEGER, day INTEGER, value REAL)"
    )
    print(f"Writing results for {len(all_results)} scenario(s) to {_db}")
    for _si, (_scen, _reps_data) in enumerate(all_results.items(), start=1):
        _n_reps = len(_reps_data)
        for _ri, (_h, _h_full, _kinds, _psi) in enumerate(_reps_data):
            for _c, _arr in _h.items():
                _cur.executemany(
                    "INSERT INTO results VALUES (?,?,?,?,?,?,?)",
                    [(_scen, _ri, _psi, _c, _kinds[_c], _d + 1, float(_v))
                     for _d, _v in enumerate(_arr)],
                )
            for _c, _sp_map in _h_full.items():
                for _spname, _arr_full in _sp_map.items():
                    # Vectorized index construction (numpy) instead of a
                    # triple-nested Python for-loop over day/age_group/
                    # risk_group -- meaningfully faster once that product
                    # runs into the hundreds of thousands of rows across many
                    # stochastic replicates.
                    _d_idx, _a_idx, _r_idx = np.indices(_arr_full.shape)
                    _cur.executemany(
                        "INSERT INTO results_full VALUES (?,?,?,?,?,?,?,?,?,?)",
                        zip(
                            itertools.repeat(_scen), itertools.repeat(_ri), itertools.repeat(_psi),
                            itertools.repeat(_c), itertools.repeat(_kinds[_c]), itertools.repeat(_spname),
                            _a_idx.ravel().tolist(), _r_idx.ravel().tolist(),
                            (_d_idx.ravel() + 1).tolist(), _arr_full.ravel().astype(float).tolist(),
                        ),
                    )
            # Progress within a scenario's replicates, so a long stochastic
            # run (hundreds of reps) doesn't look stuck between per-scenario
            # lines below.
            if _n_reps > 20 and (_ri + 1) % 20 == 0:
                print(f"  [{_si}/{len(all_results)}] {_scen}: wrote {_ri + 1}/{_n_reps} replicate(s)")
        print(f"[{_si}/{len(all_results)}] {_scen}: wrote {_n_reps} replicate(s) to {_db}")
    # build_counterfactual_tables_from_db.py's ResultsDB.arrays() filters on
    # (scenario, compartment) for every table it builds, often re-querying
    # the same scenario several times across different tables -- without
    # this index each of those is a full sequential scan of `results_full`.
    _cur.execute("CREATE INDEX idx_results_full_scenario_compartment ON results_full (scenario, compartment)")
    _cur.execute("CREATE INDEX idx_results_scenario_compartment ON results (scenario, compartment)")
    _con.commit()
    _con.close()
    print(f"Results saved to {_db}")
